// Pipeline comparison, NOT equal-quality or a hardware FPS benchmark. The new
// default reuses samples and schedules fewer probes; the reference does neither.
import {chromium} from '@playwright/test';import {createServer} from 'vite';import fs from 'node:fs';
const server=await createServer({server:{host:'127.0.0.1',port:5186}});await server.listen();const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--enable-unsafe-webgpu','--use-vulkan=swiftshader']});
try{const page=await browser.newPage({deviceScaleFactor:1});await page.route('**/src/main.js*',r=>r.fulfill({contentType:'text/javascript',body:''}));await page.goto('http://127.0.0.1:5186');const result=await page.evaluate(async()=>{
 const {settings,makeScene,updateScene,updateMs}=await import('/src/scene.js');const results=[];
 for(const [name,module,temporal] of [['v06 reference','reference-gpu',false],['v07 full refresh','gpu',false],['v07 reconstructed','gpu',true]]){
  Object.assign(settings,{scene:'large',distance:29.6,resolution:1,probeDensity:3,probeAngular:0,probes:false,bvh:true,gi:true,view:0,reflections:true,temporal,spatialFilter:temporal,probeBudget:4,shadowSamples:64,orbSamples:64,emission:4.9,orbPower:3.3,emitterSize:1.9});makeScene();
  const {GPURenderer}=await import(`/src/${module}.js`);let target;const errors=[];const canvas={clientWidth:64,clientHeight:48,width:64,height:48,getContext:()=>({configure:({device,format})=>target=device.createTexture({size:[64,48],format,usage:GPUTextureUsage.RENDER_ATTACHMENT}),getCurrentTexture:()=>target})};const renderer=await new GPURenderer().init(canvas);renderer.onError=e=>errors.push(e.message);const rows=[];
  for(let i=0;i<5;i++){await renderer.timingReady;const start=performance.now();updateScene(4+i*.05);await renderer.render();const wallMs=performance.now()-start;await renderer.timingReady;if(i>=2)rows.push({wallMs,cpuMs:renderer.cpuMs,refitMs:renderer.bvhMs,gpuMs:renderer.gpuMs,...renderer.passMs,uploadBytes:renderer.uploadBytes??null,rays:renderer.scheduledRays??renderer.probeConfig.totalRays});}
  const median=k=>rows.map(r=>r[k]).filter(Number.isFinite).sort((a,b)=>a-b)[1]??null;results.push({name,adapter:renderer.adapterInfo,errors,rows,median:Object.fromEntries(['wallMs','cpuMs','refitMs','gpuMs','visibility','cascades','shading','reconstruction','present','uploadBytes','rays'].map(k=>[k,median(k)]))});renderer.destroy();
 }return {date:new Date().toISOString(),resolution:[64,48],triangles:10008,probes:7884,angular:'base',warmup:2,samples:3,settings:{view:'Lit',reflections:true,panelSampleTarget:64,orbSampleTarget:64,emission:4.9,orbPower:3.3,emitterSize:1.9,cameraDistance:29.6,poseTimesMeasured:[4.1,4.15,4.2]},notes:'SwiftShader software GPU. Moving pose, high sample targets. Fixed order. v0.6 reference uses current scene-update cache and refit-copy micro-optimization, so is not an untouched old build. Reconstructed profile uses <=8 fresh emitter samples and a quarter-probe budget; not equal quality or equivalent per-frame work. No target hardware FPS claim.',results};
});fs.mkdirSync('docs/measurements',{recursive:true});fs.writeFileSync(process.env.COMPARE_OUTPUT||'docs/measurements/software-v07.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));}finally{await browser.close();await server.close();}
