import assert from 'node:assert/strict';
import {chromium} from '@playwright/test';
import {createServer} from 'vite';
import {settings,makeScene,updateScene,updateMs,objects,lights} from '../src/scene.js';
import {InstancedScene} from '../src/acceleration.js';
import {ProbeScheduler} from '../src/scheduler.js';
import {getProbeConfig} from '../src/probes.js';
settings.scene='large';makeScene();const scene=new InstancedScene();scene.update();assert.equal(scene.triangleCount,10008);assert.equal(scene.localTriangleCount,4020);assert.equal(scene.meshes.find(m=>m.objects.length===500).count,12);
const triangles=scene.triangles,nodes=scene.nodes;updateScene(1);scene.update();assert.equal(scene.dirtyTriangles.length,1);assert.equal(scene.dirtyTriangles[0][1],3072*20);assert.equal(scene.triangles,triangles);assert.equal(scene.nodes,nodes);updateScene(1);scene.update();assert.equal(updateMs,0);assert.equal(scene.changed,false);assert.equal(scene.dirtyTriangles.length,0);
settings.bvh=false;updateScene(2);scene.update();assert.equal(scene.refitMs,0);settings.bvh=true;scene.update();assert.ok(scene.refitMs>0);
const scheduler=new ProbeScheduler(),config=getProbeConfig();scheduler.configure(config);const seen=new Set();for(let f=0;f<4;f++){scheduler.frame++;const count=scheduler.select(0,4,false,[Infinity,Infinity,Infinity,-Infinity,-Infinity,-Infinity]);assert.equal(count,216);for(let i=0;i<count;i++)seen.add(scheduler.ids[0][i]);}assert.equal(seen.size,864);
settings.scene='atrium';makeScene();const atrium=new InstancedScene();atrium.update();assert.equal(atrium.triangleCount,9476);assert.equal(atrium.localTriangleCount,1444);assert.equal(atrium.meshes.length,9);assert.equal(objects.length,428);assert.equal(lights.length,3);assert.deepEqual(getProbeConfig().size,[24,10,22]);
assert.ok(objects.every(o=>(o.geometry.index?.count??o.geometry.attributes.position.count)%3===0&&Array.from(o.geometry.attributes.position.array).every(Number.isFinite)));
const banners=objects.filter(o=>o.kind==='atrium-banner'),bannerIndex=banners.map(o=>Array.from(o.geometry.index.array)),bannerMatrices=banners.map(o=>o.matrix.clone());updateScene(.2);atrium.update();assert.equal(atrium.dirtyTriangles.length,2);assert.ok(atrium.dirtyTriangles.every(([,length])=>length===240*20));assert.ok(banners.every((o,i)=>o.geometry.index.array.every((v,j)=>v===bannerIndex[i][j])&&o.matrix.equals(bannerMatrices[i])));
console.log('✓ Atrium: triangle-only architecture, instanced columns/walls, three mesh lights, two connected deforming banners');
console.log('✓ Instancing: 500 shared cubes, local BLAS reuse, deform-only upload, paused cache, brute bypass; hard probe budget and coverage');
const server=await createServer({server:{host:'127.0.0.1',port:5184,strictPort:true}});await server.listen();const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--enable-unsafe-webgpu','--use-vulkan=swiftshader']});
try{const page=await browser.newPage({deviceScaleFactor:1});await page.route('**/src/main.js*',r=>r.fulfill({contentType:'text/javascript',body:''}));await page.goto('http://127.0.0.1:5184');
const result=await page.evaluate(async()=>{
 const {settings,makeScene,updateScene,objects}=await import('/src/scene.js');const {GPURenderer}=await import('/src/gpu.js');const {InstancedScene}=await import('/src/acceleration.js');const {instancedCommon,visibilityHelpers}=await import('/src/modern-shaders.js');const THREE=await import('/node_modules/three/build/three.module.js');
 Object.assign(settings,{scene:'primitives',resolution:1,running:false,probes:false,gi:false,temporal:false,spatialFilter:false,shadowSamples:4,orbSamples:16,probeDensity:0,probeAngular:0,bvh:true});makeScene();let target,device;const errors=[];
 const canvas={clientWidth:64,clientHeight:48,width:64,height:48,getContext:()=>({configure:({device:d,format})=>{device=d;target=d.createTexture({size:[64,48],format,usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.COPY_SRC});},getCurrentTexture:()=>target})};const renderer=await new GPURenderer().init(canvas);renderer.onError=e=>errors.push(e.message);
 const read=async(buffer,bytes)=>{const out=device.createBuffer({size:bytes,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});const enc=device.createCommandEncoder();enc.copyBufferToBuffer(buffer,0,out,0,bytes);device.queue.submit([enc.finish()]);await out.mapAsync(GPUMapMode.READ);const data=new Uint8Array(out.getMappedRange()).slice();out.unmap();out.destroy();return data;};
 const pixels=async(texture,bpp)=>{const stride=Math.ceil(64*bpp/256)*256,buffer=device.createBuffer({size:stride*48,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});const enc=device.createCommandEncoder();enc.copyTextureToBuffer({texture},{buffer,bytesPerRow:stride},[64,48]);device.queue.submit([enc.finish()]);await buffer.mapAsync(GPUMapMode.READ);const data=new Uint8Array(buffer.getMappedRange()).slice();buffer.unmap();buffer.destroy();return data;};
 await renderer.render();const accelerated=await pixels(renderer.texture,4);settings.bvh=false;await renderer.render();const brute=await pixels(renderer.texture,4);const bruteDifference=accelerated.reduce((n,v,i)=>n+(v!==brute[i]?1:0),0);const bruteRefit=renderer.bvhMs;settings.bvh=true;await renderer.render();
 // Compare rasterized triangle/barycentric reconstruction with independent
 // closest-triangle camera rays (not a screenshot approximation). Exclude
 // centers within 0.2 pixels of either triangle edge: fixed-function subpixel
 // coverage and floating-point ray intersection do not have identical edge rules.
 const rayCommon=instancedCommon.replace('t.info.x,t.info.y,min(', 't.info.x,f32(index),min(').replace('r.metal=nodeData[i+9u].x;r.floor=nodeData[i+9u].y;', 'r.metal=f32(i);');
 const rayModule=device.createShaderModule({code:rayCommon+visibilityHelpers+`fn project(p:vec3f)->vec2f{let d=p-u.eye.xyz;let z=dot(d,u.forward.xyz);return (vec2f(dot(d,u.right.xyz)/(z*u.screen.x/u.screen.y*.38),-dot(d,u.up.xyz)/(z*.38))*.5+.5)*u.screen.xy;}
 fn edgePixels(index:u32,instance:u32,p:vec2f)->f32{let t=tris[index];let m=worldMatrix(instance);let a=project((m*vec4f(t.a.xyz,1)).xyz);let b=project((m*vec4f(t.b.xyz,1)).xyz);let c=project((m*vec4f(t.c.xyz,1)).xyz);let ab=b-a;let bc=c-b;let ca=a-c;return min(abs(ab.x*(p-a).y-ab.y*(p-a).x)/length(ab),min(abs(bc.x*(p-b).y-bc.y*(p-b).x)/length(bc),abs(ca.x*(p-c).y-ca.y*(p-c).x)/length(ca)));}
 @group(0) @binding(6) var<storage,read_write> output:array<vec4f>;@compute @workgroup_size(8,8) fn main(@builtin(global_invocation_id) id:vec3u){if(any(id.xy>=vec2u(u.screen.xy))){return;}let uv=(vec2f(id.xy)+.5)/u.screen.xy*2.-1.;let rd=normalize(u.forward.xyz+u.right.xyz*uv.x*u.screen.x/u.screen.y*.38-u.up.xyz*uv.y*.38);let ray=trace(u.eye.xyz,rd,.03,500.);let v=loadVisibility(vec2i(id.xy));var value=vec4f(0);if(v.y>.5){let h=visibleHit(v,u.eye.xyz,rd);if(min(edgePixels(u32(ray.floor),u32(ray.metal),vec2f(id.xy)+.5),edgePixels(u32(v.y)-1u,u32(v.x),vec2f(id.xy)+.5))>.2){value=vec4f(abs(ray.t-h.t),distance(ray.normal,h.normal),distance(ray.color,h.color),1.);}}else if(ray.t<500.&&edgePixels(u32(ray.floor),u32(ray.metal),vec2f(id.xy)+.5)>.2){value=vec4f(999,ray.edge,ray.t,1);}output[id.x+id.y*u32(u.screen.x)]=value;}`});
 const rp=await device.createComputePipelineAsync({layout:'auto',compute:{module:rayModule,entryPoint:'main'}}),ro=device.createBuffer({size:64*48*16,usage:GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC});const rb=renderer.bind(rp,{0:renderer.uniform,1:renderer.sceneBuffers.triangles,7:renderer.sceneBuffers.nodes,10:renderer.visibility.createView(),6:ro});let enc=device.createCommandEncoder(),pass=enc.beginComputePass();pass.setPipeline(rp);pass.setBindGroup(0,rb);pass.dispatchWorkgroups(8,6);pass.end();device.queue.submit([enc.finish()]);const rayData=new Float32Array((await read(ro,64*48*16)).buffer);const rasterNormalError=Math.max(...Array.from({length:64*48},(_,i)=>rayData[i*4+1]));const rasterMaterialError=Math.max(...Array.from({length:64*48},(_,i)=>rayData[i*4+2]));const rasterCompared=Array.from({length:64*48},(_,i)=>rayData[i*4+3]).filter(v=>v===1).length;const rasterOutliers=Array.from({length:64*48},(_,i)=>({x:i%64,y:Math.floor(i/64),error:rayData[i*4],normal:rayData[i*4+1],material:rayData[i*4+2]})).filter(v=>v.error>.002);const rasterError=Math.max(...Array.from({length:64*48},(_,i)=>rayData[i*4]));ro.destroy();
 // History accumulates only for matching static surfaces; emitter settings reset
 // it, geometry changes reject it, resize/scene changes replace it.
 settings.temporal=true;settings.spatialFilter=true;settings.gi=true;await renderer.render();const fullRays=renderer.scheduledRays;for(let i=0;i<12;i++)await renderer.render();const partialRays=renderer.scheduledRays;
 const half=x=>{const sign=x&0x8000?-1:1,e=(x>>10)&31,m=x&1023;return sign*(e===0?2**-14*m/1024:2**(e-15)*(1+m/1024));};
 const historyCounts=async()=>{const raw=new Uint16Array((await pixels(renderer.histories[(renderer.frameId-1)%2].color,8)).buffer);return Array.from({length:64*48},(_,i)=>half(raw[i*4+3]));};const historyMax=Math.max(...await historyCounts());updateScene(.5);await renderer.render();const lightingJumpReset=Math.max(...await historyCounts());const movingHistory=await historyCounts(),movingIds=new Uint32Array((await pixels(renderer.visibility,8)).buffer);let movingPixels=0,movingHistoryRejected=true;for(let i=0;i<64*48;i++){const instance=movingIds[i*2];if(movingIds[i*2+1]&&renderer.acceleration.nodes[instance*4+39]>.5){movingPixels++;if(movingHistory[i]!==1)movingHistoryRejected=false;}}
 settings.orbPower=2;await updateScene(0);await renderer.render();const resetMax=Math.max(...await historyCounts());
 settings.scene='large';settings.distance=29.6;makeScene();await renderer.render();const sceneResetMax=Math.max(...await historyCounts());const hall={triangles:renderer.triangleCount,local:renderer.localTriangleCount,meshCount:renderer.acceleration.meshes.length};updateScene(1);await renderer.render();const movingUpload=renderer.uploadBytes;await renderer.render();await renderer.render();const pausedUpload=renderer.uploadBytes;
 Object.assign(settings,{scene:'atrium',distance:24.8,cameraPitch:-.20,cameraYaw:.055,temporal:false,spatialFilter:false,view:1});makeScene();await renderer.render();const atriumLit=await pixels(renderer.texture,4);const atriumTriangles=renderer.triangleCount,atriumLocal=renderer.localTriangleCount;settings.wireframe=true;await renderer.render();const atriumEdges=await pixels(renderer.texture,4);const atriumEdgeChanges=atriumEdges.reduce((sum,v,i)=>sum+(v!==atriumLit[i]?1:0),0);settings.wireframe=false;settings.temporal=true;settings.spatialFilter=true;settings.cameraPitch=0;settings.cameraYaw=0;
 settings.scene='primitives';settings.distance=14.8;settings.view=4;settings.probeDensity=2;settings.probeAngular=1;makeScene();await renderer.render();const highRays=renderer.scheduledRays;settings.probeDensity=3;await renderer.render();const ultraRays=renderer.scheduledRays;const oldTexture=renderer.texture;canvas.clientWidth=80;canvas.clientHeight=56;await renderer.render();const resized=renderer.texture!==oldTexture&&renderer.texture.width===80&&renderer.texture.height===56;const resizeResetMax=Math.max(...await historyCounts());
 // Uniform white probe field on the far side of an opaque wall. Test both the
 // final surface connection and displaced coarse-interval endpoint connection.
 objects.length=0;const wall={geometry:new THREE.BoxGeometry(.05,4,4),matrix:new THREE.Matrix4(),mat:{color:[1,1,1],emission:0,metal:0},kind:'fixture'};objects.push(wall);let fixture=new InstancedScene();fixture.update();
 const buffer=(size,usage=GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST)=>device.createBuffer({size,usage});const uniform=buffer(352,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST),tri=buffer(128*80),node=buffer(1048576),near=buffer(256*16),mid=buffer(256*16),far=buffer(256*16),irr=buffer(32*16),out=buffer(16,GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC);
 const u=new Float32Array(88);u[23]=1;u[28]=1;u[29]=fixture.tree.length;u.set([-2,-1,-1,0],36);u.set([4,2,2,0],40);u.set([2,1,1,4],44);u.set([1,1,1,8],48);u.set([1,1,1,16],52);u.set([2,4,8,0],56);u[80]=fixture.instanceBase;device.queue.writeBuffer(uniform,0,u);device.queue.writeBuffer(mid,0,new Float32Array(256*4).fill(1));const ir=new Float32Array(32*4);for(let i=6;i<12;i++)ir.set([1,1,1,1],i*4);for(let i=12;i<16;i++)ir[i*4]=1;device.queue.writeBuffer(irr,0,ir);
 const fm=device.createShaderModule({code:instancedCommon+`@group(0) @binding(6) var<storage,read_write> output:array<vec4f>;@compute @workgroup_size(1) fn main(){output[0]=vec4f(sampleIrradiance(vec3f(-.25,0,0),vec3f(1,0,0)).x,coarseRadiance(1u,vec3f(-1,0,0),vec2f(0,.5)).x,suitableProbe(vec3f(0),.7),1);}`});const fp=await device.createComputePipelineAsync({layout:'auto',compute:{module:fm,entryPoint:'main'}});const fb=renderer.bind(fp,{0:uniform,1:tri,2:near,3:mid,4:far,5:irr,6:out,7:node});
 const query=async()=>{device.queue.writeBuffer(tri,0,fixture.triangles);device.queue.writeBuffer(node,0,fixture.nodes);const enc=device.createCommandEncoder(),p=enc.beginComputePass();p.setPipeline(fp);p.setBindGroup(0,fb);p.dispatchWorkgroups(1);p.end();device.queue.submit([enc.finish()]);return Array.from(new Float32Array((await read(out,16)).buffer));};
 const wallBlocked=await query();wall.matrix.makeTranslation(5,0,0);fixture.update();const wallClear=await query();wall.matrix.makeScale(.016,1,1);fixture.update();const thinBlocked=await query();wall.matrix.makeScale(30,.5,.5);fixture.update();const enclosedProbe=await query();
 // Deform a connected wall mesh by changing vertices, not its instance matrix.
 wall.matrix.identity();const positions=wall.geometry.attributes.position;for(let i=0;i<positions.count;i++)positions.setX(i,positions.getX(i)+5);positions.needsUpdate=true;fixture.update();const deformedClear=await query();
 // A connected, non-rigid sheet uses the same fixed index buffer and matrix.
 wall.geometry=new THREE.PlaneGeometry(4,4,4,4);wall.matrix.makeRotationY(Math.PI/2);fixture=new InstancedScene();fixture.update();u[80]=fixture.instanceBase;u[29]=fixture.tree.length;device.queue.writeBuffer(uniform,0,u);const sheetBlocked=await query();const sheetPositions=wall.geometry.attributes.position,indexBefore=Array.from(wall.geometry.index.array);for(let i=0;i<sheetPositions.count;i++)sheetPositions.setZ(i,3+.3*Math.sin(sheetPositions.getY(i)*2));sheetPositions.needsUpdate=true;fixture.update();const sheetMoved=await query();const sheetTopologyUnchanged=indexBefore.every((x,i)=>x===wall.geometry.index.array[i]);
 for(const b of [uniform,tri,node,near,mid,far,irr,out])b.destroy();await renderer.timingReady;const passTimes=renderer.passMs;renderer.destroy();return {errors,bruteDifference,bruteRefit,rasterError,rasterNormalError,rasterMaterialError,rasterCompared,rasterOutliers:rasterOutliers.slice(0,20),fullRays,partialRays,historyMax,resetMax,lightingJumpReset,movingPixels,movingHistoryRejected,sceneResetMax,hall,movingUpload,pausedUpload,atriumTriangles,atriumLocal,atriumEdgeChanges,highRays,ultraRays,resized,resizeResetMax,wallBlocked,wallClear,thinBlocked,enclosedProbe,deformedClear,sheetBlocked,sheetMoved,sheetTopologyUnchanged,passTimes};
});
console.log(result);assert.deepEqual(result.errors,[]);assert.equal(result.bruteDifference,0);assert.equal(result.bruteRefit,0);assert.ok(result.rasterError<.002);assert.ok(result.rasterNormalError<.0001);assert.ok(result.rasterMaterialError<.0001);assert.ok(result.rasterCompared>2000);assert.equal(result.fullRays,7168);assert.equal(result.partialRays,1792);assert.ok(result.historyMax>=8);assert.equal(result.resetMax,1);assert.equal(result.sceneResetMax,1);assert.equal(result.lightingJumpReset,1);assert.ok(result.movingPixels>0);assert.ok(result.movingHistoryRejected);assert.ok(result.sheetTopologyUnchanged);assert.equal(result.sheetBlocked[0],0);assert.equal(result.sheetBlocked[1],0);assert.equal(result.sheetBlocked[2],0);assert.equal(result.enclosedProbe[2],0);assert.ok(Math.abs(result.sheetMoved[0]-.375)<.0001);assert.equal(result.sheetMoved[1],1);assert.equal(result.hall.triangles,10008);assert.equal(result.hall.local,4020);assert.ok(result.movingUpload>result.pausedUpload);assert.equal(result.pausedUpload,0);assert.equal(result.atriumTriangles,9476);assert.equal(result.atriumLocal,1444);assert.ok(result.atriumEdgeChanges>100);assert.equal(result.highRays,229376);assert.equal(result.ultraRays,774144);assert.ok(result.resized);assert.equal(result.resizeResetMax,1);
for(const k of ['wallBlocked','thinBlocked'])assert.deepEqual(result[k],[0,0,0,1]);for(const k of ['wallClear','deformedClear']){assert.ok(Math.abs(result[k][0]-.375)<.0001);assert.equal(result[k][1],1);assert.equal(result[k][2],1);}assert.ok(result.passTimes.visibility>=0);assert.ok(result.passTimes.reconstruction>=0);
console.log('✓ GPU visibility raster vs camera-ray reference; instanced BVH/brute equality; budgeted updates; temporal accumulation/reset; opaque/thin wall and deforming blocker fixtures');
}finally{await browser.close();await server.close();}
