/**
 * FRONTIER — Automotive Material Library
 *
 * Every entry is a preset: a shader family plus a set of parameter values tuned
 * to real-world automotive specs (film builds in µm, yarn counts per metre,
 * tread block pitches, glass absorption coefficients...).
 */

export const CATEGORIES = [
	{ id: 'paint',     label: 'Paint & Coat' },
	{ id: 'brakes',    label: 'Brakes' },
	{ id: 'ceramics',  label: 'Ceramics' },
	{ id: 'fabric',    label: 'Fabric & Trim' },
	{ id: 'rubber',    label: 'Rubber' },
	{ id: 'glass',     label: 'Glass & Optics' },
	{ id: 'metal',     label: 'Metals' },
	{ id: 'composite', label: 'Composites' },
];

const P = ( id, name, family, category, notes, values ) => ( { id, name, family, category, notes, values } );

export const MATERIAL_LIBRARY = [

	/* ============================== PAINT ============================== */
	P( 'paint-silver-metallic', 'Metallic Silver Flake', 'paint', 'paint',
		'Classic 3-stage silver. ~30 µm basecoat, 45 µm clear. Coarse aluminium flake.',
		{
			baseColor: '#c6cad0', edgeColor: '#5f666e', metallic: 1, roughness: 0.24,
			flop: 0.62, depthFog: 0.5, flakeDensity: 64, flakeSpread: 0.3, flakeStrength: 0.88,
			flakeColor: '#e3e7ec', pearlColor: '#cfe4ff', pearl: 0.06,
			sparkle: 1.35, sparkleSharp: 0.022, flakeSeed: 17,
			paintDepth: 48, coatStrength: 1, coatRoughness: 0.028, coatIOR: 1.52,
			orangePeel: 0.2, swirl: 0.06, chip: 0,
		} ),
	P( 'paint-candy-rosso', 'Candy Pearl Rosso', 'paint', 'paint',
		'Translucent candy over a metallic ground. Deep film build, strong flop.',
		{
			baseColor: '#9c1220', edgeColor: '#25060a', metallic: 0.9, roughness: 0.2,
			flop: 0.85, depthFog: 0.72, flakeDensity: 38, flakeSpread: 0.42, flakeStrength: 0.7,
			flakeColor: '#ffd7c2', pearlColor: '#ff8a3d', pearl: 0.42,
			sparkle: 0.95, sparkleSharp: 0.034, flakeSeed: 41,
			paintDepth: 82, coatStrength: 1, coatRoughness: 0.018, coatIOR: 1.56,
			orangePeel: 0.12, swirl: 0.04, chip: 0,
		} ),
	P( 'paint-midnight-blue', 'Midnight Blue Metal Flake', 'paint', 'paint',
		'Dark blue metallic. Fine flake, low flop, very wet-looking clear.',
		{
			baseColor: '#0f1f42', edgeColor: '#04070f', metallic: 0.95, roughness: 0.22,
			flop: 0.55, depthFog: 0.66, flakeDensity: 78, flakeSpread: 0.26, flakeStrength: 0.9,
			flakeColor: '#b9c8ea', pearlColor: '#6fa8ff', pearl: 0.14,
			sparkle: 1.2, sparkleSharp: 0.019, flakeSeed: 63,
			paintDepth: 60, coatStrength: 1, coatRoughness: 0.022, coatIOR: 1.54,
			orangePeel: 0.16, swirl: 0.05, chip: 0,
		} ),
	P( 'paint-xirallic-gold', 'Xirallic Solar Gold', 'paint', 'paint',
		'Mica (xirallic) pigment — interference flakes that shift hue with angle.',
		{
			baseColor: '#a9791f', edgeColor: '#3a2405', metallic: 0.85, roughness: 0.25,
			flop: 0.78, depthFog: 0.4, flakeDensity: 52, flakeSpread: 0.2, flakeStrength: 0.95,
			flakeColor: '#ffe9a8', pearlColor: '#ff7a45', pearl: 0.85,
			sparkle: 1.5, sparkleSharp: 0.016, flakeSeed: 8,
			paintDepth: 56, coatStrength: 1, coatRoughness: 0.02, coatIOR: 1.55,
			orangePeel: 0.14, swirl: 0.03, chip: 0,
		} ),
	P( 'paint-chameleon', 'Chameleon Violaviolet', 'paint', 'paint',
		'Colour-shift mica. Near-total flop with a teal-to-violet travel.',
		{
			baseColor: '#2b1550', edgeColor: '#0a3c42', metallic: 0.8, roughness: 0.18,
			flop: 1, depthFog: 0.3, flakeDensity: 60, flakeSpread: 0.16, flakeStrength: 0.92,
			flakeColor: '#7ce8d8', pearlColor: '#b06bff', pearl: 0.95,
			sparkle: 1.1, sparkleSharp: 0.02, flakeSeed: 77,
			paintDepth: 70, coatStrength: 1, coatRoughness: 0.016, coatIOR: 1.58,
			orangePeel: 0.1, swirl: 0.02, chip: 0,
		} ),
	P( 'paint-solid-rosso', 'Solid Gloss Rosso Corsa', 'paint', 'paint',
		'Non-metallic solid. No flake, pure pigment and clear — the flop is minimal.',
		{
			baseColor: '#b3121c', edgeColor: '#7d0a12', metallic: 0, roughness: 0.3,
			flop: 0.18, depthFog: 0.12, flakeDensity: 0, flakeSpread: 0.3, flakeStrength: 0,
			flakeColor: '#ffffff', pearlColor: '#ffffff', pearl: 0,
			sparkle: 0, sparkleSharp: 0.03, flakeSeed: 1,
			paintDepth: 55, coatStrength: 1, coatRoughness: 0.024, coatIOR: 1.53,
			orangePeel: 0.24, swirl: 0.07, chip: 0,
		} ),
	P( 'paint-nardo-satin', 'Nardo Grey Satin Wrap', 'paint', 'paint',
		'Matte wrap film. High coat roughness, no clear gloss, textured surface.',
		{
			baseColor: '#7d8186', edgeColor: '#8d9196', metallic: 0.05, roughness: 0.62,
			flop: 0.1, depthFog: 0.05, flakeDensity: 0, flakeSpread: 0.3, flakeStrength: 0,
			flakeColor: '#ffffff', pearlColor: '#ffffff', pearl: 0,
			sparkle: 0, sparkleSharp: 0.05, flakeSeed: 1,
			paintDepth: 12, coatStrength: 0.38, coatRoughness: 0.52, coatIOR: 1.46,
			orangePeel: 0.42, swirl: 0, chip: 0,
		} ),
	P( 'paint-brg', 'British Racing Green', 'paint', 'paint',
		'Deep metallic green, very high film build — reads almost black at the edges.',
		{
			baseColor: '#0d3b2a', edgeColor: '#02120c', metallic: 0.88, roughness: 0.21,
			flop: 0.9, depthFog: 0.78, flakeDensity: 70, flakeSpread: 0.34, flakeStrength: 0.8,
			flakeColor: '#a8dcc0', pearlColor: '#e8d78a', pearl: 0.22,
			sparkle: 1.05, sparkleSharp: 0.024, flakeSeed: 29,
			paintDepth: 88, coatStrength: 1, coatRoughness: 0.019, coatIOR: 1.55,
			orangePeel: 0.15, swirl: 0.05, chip: 0.05,
		} ),
	P( 'paint-caliper-red', 'Caliper Gloss Red', 'paint', 'paint',
		'Hammer-tone caliper paint. Slight flake, heavy orange peel, heat-cured.',
		{
			baseColor: '#a5141c', edgeColor: '#6b0a10', metallic: 0.22, roughness: 0.26,
			flop: 0.3, depthFog: 0.2, flakeDensity: 22, flakeSpread: 0.55, flakeStrength: 0.5,
			flakeColor: '#d9dee4', pearlColor: '#ffffff', pearl: 0.02,
			sparkle: 0.35, sparkleSharp: 0.05, flakeSeed: 52,
			paintDepth: 30, coatStrength: 1, coatRoughness: 0.05, coatIOR: 1.5,
			orangePeel: 0.55, swirl: 0, chip: 0,
		} ),
	P( 'paint-weathered', 'Faded Oxidised Red', 'paint', 'paint',
		'Neglected single-stage paint: UV-chalked, swirled, chipped at the edges.',
		{
			baseColor: '#8e4a44', edgeColor: '#a08d86', metallic: 0.05, roughness: 0.66,
			flop: 0.25, depthFog: 0.1, flakeDensity: 0, flakeSpread: 0.3, flakeStrength: 0,
			flakeColor: '#ffffff', pearlColor: '#ffffff', pearl: 0,
			sparkle: 0, sparkleSharp: 0.06, flakeSeed: 1,
			paintDepth: 8, coatStrength: 0.22, coatRoughness: 0.4, coatIOR: 1.44,
			orangePeel: 0.65, swirl: 0.55, chip: 0.5,
		} ),

	/* ============================== BRAKES ============================== */
	P( 'brake-cast-iron', 'Cast Iron Rotor', 'brake', 'brakes',
		'Vented cast iron disc. Turned finish, flash rust on the hat, pad-polished band.',
		{
			discType: 'iron', baseColor: '#6d7075', rustColor: '#7c3f1d',
			metallic: 0.96, roughness: 0.4, grooveDensity: 55, grooveStrength: 0.7,
			aniso: 0.78, wear: 0.38, speckle: 0.42, speckleScale: 480,
			drill: 0, drillCount: 18, drillRings: 3, drillRadius: 4.5,
			rust: 0.14, heat: 0, heatSpread: 0.6, glow: 0, discRadius: 0.16,
		} ),
	P( 'brake-carbon-ceramic', 'Carbon-Ceramic Disc', 'brake', 'brakes',
		'C/SiC composite. Near-black, matte, chopped-fibre speckle, no anisotropy.',
		{
			discType: 'ceramic', baseColor: '#17181c', rustColor: '#3a3733',
			metallic: 0.2, roughness: 0.52, grooveDensity: 20, grooveStrength: 0.2,
			aniso: 0.1, wear: 0.25, speckle: 0.85, speckleScale: 900,
			drill: 0.85, drillCount: 24, drillRings: 3, drillRadius: 5.5,
			rust: 0, heat: 0.1, heatSpread: 0.5, glow: 0, discRadius: 0.19,
		} ),
	P( 'brake-drilled-hot', 'Drilled Steel — Hot', 'brake', 'brakes',
		'Post-lap steel disc glowing through the temper colours.',
		{
			discType: 'steel', baseColor: '#7c8085', rustColor: '#8a4a22',
			metallic: 0.98, roughness: 0.32, grooveDensity: 70, grooveStrength: 0.55,
			aniso: 0.85, wear: 0.72, speckle: 0.15, speckleScale: 600,
			drill: 0.95, drillCount: 20, drillRings: 4, drillRadius: 4.0,
			rust: 0.02, heat: 0.62, heatSpread: 0.75, glow: 0.12, discRadius: 0.16,
		} ),
	P( 'brake-rusty', 'Rusted Rotor (Parked)', 'brake', 'brakes',
		'A disc left out for a month — heavy flash rust everywhere but the pad sweep.',
		{
			discType: 'iron', baseColor: '#63666b', rustColor: '#8a4a20',
			metallic: 0.94, roughness: 0.44, grooveDensity: 40, grooveStrength: 0.35,
			aniso: 0.4, wear: 0.85, speckle: 0.5, speckleScale: 420,
			drill: 0.5, drillCount: 16, drillRings: 3, drillRadius: 5.0,
			rust: 0.72, heat: 0, heatSpread: 0.5, glow: 0, discRadius: 0.16,
		} ),
	P( 'brake-pad', 'Brake Pad Friction Material', 'composite', 'brakes',
		'Resin-bonded semi-metallic compound with steel fibre and abrasive grit.',
		{
			layup: 'grain', fiberColor: '#2b2723', resinColor: '#4b443a', sheenColor: '#8d8578',
			metallic: 0.42, roughness: 0.76, weaveScale: 420, weaveStrength: 0.55,
			filament: 0.35, resin: 0.5, coatStrength: 0, coatRoughness: 0.6,
			orangePeel: 0.2, sheen: 0.12, seed: 21,
		} ),
	P( 'brake-hat-alloy', 'Rotor Hat — Machined Alloy', 'metal', 'brakes',
		'The aluminium centre hat: concentric machined, lightly anodised.',
		{
			finish: 'machined', baseColor: '#a9aeb4', patinaColor: '#6d6a5a',
			metallic: 1, roughness: 0.22, brushScale: 260, brushStrength: 0.55,
			brushAngle: 0, aniso: 0.66, patina: 0.05, heat: 0.12,
			coatStrength: 0.15, coatRoughness: 0.12, seed: 4,
		} ),

	/* ============================== CERAMICS ============================== */
	P( 'ceramic-glaze', 'Glazed Porcelain', 'ceramic', 'ceramics',
		'High-gloss vitreous glaze over a warm body. Used for lamp reflectors.',
		{
			glazeColor: '#f3f0e9', bodyColor: '#c3baa9', speckColor: '#4b4038',
			roughness: 0.055, coatStrength: 1, coatRoughness: 0.012, coatIOR: 1.56,
			speckle: 0.12, speckleScale: 520, crazing: 0, crazingScale: 90,
			microBump: 0.12, subsurface: 0.42, thickness: 0.006, seed: 7,
		} ),
	P( 'ceramic-technical', 'Technical Alumina (Matte)', 'ceramic', 'ceramics',
		'96% Al₂O₃ substrate — dry, speckled, almost no glaze.',
		{
			glazeColor: '#dcd8ce', bodyColor: '#b7b1a4', speckColor: '#6a6157',
			roughness: 0.44, coatStrength: 0.12, coatRoughness: 0.4, coatIOR: 1.62,
			speckle: 0.55, speckleScale: 1100, crazing: 0, crazingScale: 90,
			microBump: 0.55, subsurface: 0.18, thickness: 0.004, seed: 19,
		} ),
	P( 'ceramic-zirconia', 'Polished Zirconia', 'ceramic', 'ceramics',
		'Dental/bearing grade — mirror-polished, faintly translucent.',
		{
			glazeColor: '#e9e6df', bodyColor: '#cfcbc2', speckColor: '#8b867c',
			roughness: 0.018, coatStrength: 1, coatRoughness: 0.006, coatIOR: 2.05,
			speckle: 0.04, speckleScale: 900, crazing: 0, crazingScale: 90,
			microBump: 0.04, subsurface: 0.55, thickness: 0.003, seed: 33,
		} ),
	P( 'ceramic-crazed', 'Crazed Ceramic Insulator', 'ceramic', 'ceramics',
		'Heat-cycled insulator with a visible glaze crackle network.',
		{
			glazeColor: '#e5e0d4', bodyColor: '#a89f8c', speckColor: '#40392f',
			roughness: 0.16, coatStrength: 0.85, coatRoughness: 0.07, coatIOR: 1.54,
			speckle: 0.3, speckleScale: 700, crazing: 0.55, crazingScale: 140,
			microBump: 0.4, subsurface: 0.3, thickness: 0.008, seed: 51,
		} ),

	/* ============================== FABRIC ============================== */
	P( 'fabric-alcantara', 'Alcantara / Suede', 'fabric', 'fabric',
		'Microfibre suede. Strong nap — reads lighter with the pile, darker against it.',
		{
			weave: 'suede', fiberColor: '#2a2d33', sheenColor: '#aab2c0',
			roughness: 0.88, weaveScale: 560, weaveStrength: 0.3, yarnTwist: 0.1,
			fuzz: 0.85, fuzzRoughness: 0.52, nap: 0.85, napAngle: 35,
			lint: 0.35, backscatter: 0.4, seed: 3,
		} ),
	P( 'fabric-seatcloth', 'Woven Seat Cloth', 'fabric', 'fabric',
		'2×2 twill polyester seat insert, ~1.8 mm yarn pitch.',
		{
			weave: 'twill', fiberColor: '#333841', sheenColor: '#98a3b4',
			roughness: 0.84, weaveScale: 620, weaveStrength: 0.85, yarnTwist: 0.6,
			fuzz: 0.5, fuzzRoughness: 0.42, nap: 0.2, napAngle: 0,
			lint: 0.4, backscatter: 0.28, seed: 12,
		} ),
	P( 'fabric-carpet', 'Loop-Pile Carpet', 'fabric', 'fabric',
		'Footwell carpet — dense loop knit, heavy fuzz, dust in the pile.',
		{
			weave: 'knit', fiberColor: '#22242a', sheenColor: '#7d8592',
			roughness: 0.94, weaveScale: 1400, weaveStrength: 0.7, yarnTwist: 0.85,
			fuzz: 0.95, fuzzRoughness: 0.65, nap: 0.35, napAngle: 90,
			lint: 0.6, backscatter: 0.35, seed: 27,
		} ),
	P( 'fabric-belt', 'Seatbelt Webbing', 'fabric', 'fabric',
		'Tight plain-weave nylon strap, low fuzz, high tensile sheen.',
		{
			weave: 'plain', fiberColor: '#1e2126', sheenColor: '#b9c2cf',
			roughness: 0.72, weaveScale: 1500, weaveStrength: 0.55, yarnTwist: 0.35,
			fuzz: 0.22, fuzzRoughness: 0.3, nap: 0.05, napAngle: 0,
			lint: 0.15, backscatter: 0.18, seed: 44,
		} ),
	P( 'fabric-jacquard', 'Jacquard Wool Blend', 'fabric', 'fabric',
		'Heritage wool trim — coarse yarn, warm sheen, pronounced relief.',
		{
			weave: 'twill', fiberColor: '#4a3b31', sheenColor: '#d8bda0',
			roughness: 0.9, weaveScale: 340, weaveStrength: 1, yarnTwist: 0.9,
			fuzz: 0.7, fuzzRoughness: 0.6, nap: 0.4, napAngle: 120,
			lint: 0.55, backscatter: 0.45, seed: 61,
		} ),

	/* ============================== RUBBER ============================== */
	P( 'rubber-tread', 'Tyre Tread Compound', 'rubber', 'rubber',
		'Directional block tread with sipes, ~38 mm block pitch, dusty crevices.',
		{
			pattern: 'tread', baseColor: '#15161a', sheenColor: '#4c525a', dustColor: '#6f6659',
			roughness: 0.74, microBump: 0.55, microScale: 620, treadScale: 26,
			treadDepth: 0.95, sipe: 0.62, sheen: 0.3, sheenRoughness: 0.55,
			subsurface: 0.16, dust: 0.2, seed: 11,
			projection: 'uv', uvScaleX: 2.15, uvScaleY: 0.115,
		} ),
	P( 'rubber-sidewall', 'Tyre Sidewall', 'rubber', 'rubber',
		'Moulded sidewall — fine pebble texture, slight bloom, low sheen.',
		{
			pattern: 'pebble', baseColor: '#101114', sheenColor: '#3f454d', dustColor: '#5f5b53',
			roughness: 0.8, microBump: 0.7, microScale: 900, treadScale: 90,
			treadDepth: 0.35, sipe: 0, sheen: 0.2, sheenRoughness: 0.7,
			subsurface: 0.1, dust: 0.3, seed: 18,
		} ),
	P( 'rubber-epdm', 'EPDM Weatherstrip', 'rubber', 'rubber',
		'Extruded door seal — ribbed profile, satin, slightly bloomed.',
		{
			pattern: 'ribbed', baseColor: '#0d0e10', sheenColor: '#39404a', dustColor: '#6a655c',
			roughness: 0.62, microBump: 0.4, microScale: 700, treadScale: 22,
			treadDepth: 0.7, sipe: 0, sheen: 0.35, sheenRoughness: 0.5,
			subsurface: 0.08, dust: 0.22, seed: 23,
		} ),
	P( 'rubber-mat', 'Rubber Floor Mat', 'rubber', 'rubber',
		'Heel-pad pebble grain with trapped dust.',
		{
			pattern: 'pebble', baseColor: '#1a1b1e', sheenColor: '#454b53', dustColor: '#7a7166',
			roughness: 0.7, microBump: 0.6, microScale: 520, treadScale: 130,
			treadDepth: 0.6, sipe: 0, sheen: 0.22, sheenRoughness: 0.6,
			subsurface: 0.12, dust: 0.4, seed: 36,
		} ),
	P( 'rubber-smooth', 'Smooth Moulded Rubber', 'rubber', 'rubber',
		'Bellows / grommet — almost featureless, faint mould texture.',
		{
			pattern: 'smooth', baseColor: '#131417', sheenColor: '#4a5058', dustColor: '#666058',
			roughness: 0.58, microBump: 0.35, microScale: 1200, treadScale: 40,
			treadDepth: 0.2, sipe: 0, sheen: 0.4, sheenRoughness: 0.45,
			subsurface: 0.2, dust: 0.05, seed: 48,
		} ),

	/* ============================== GLASS ============================== */
	P( 'glass-windshield', 'Laminated Windshield', 'glass', 'glass',
		'4.76 mm laminated float glass. Green iron tint, faint AR coating, wiper arcs.',
		{
			tintColor: '#dcefe4', edgeColor: '#63bd8a', tint: 0.2, transmission: 1,
			roughness: 0.008, ior: 1.52, thickness: 0.00476, dispersion: 1.2,
			absorption: 2.2, coating: 0.22, coatThickness: 260,
			scratch: 0.1, wiper: 0.14, frost: 0, seed: 5,
		} ),
	P( 'glass-privacy', 'Privacy Glass', 'glass', 'glass',
		'Factory tinted rear screen — heavy absorption, near-black from outside.',
		{
			tintColor: '#0c1013', edgeColor: '#1b2a26', tint: 0.9, transmission: 1,
			roughness: 0.02, ior: 1.52, thickness: 0.0038, dispersion: 0.6,
			absorption: 14, coating: 0.1, coatThickness: 200,
			scratch: 0.06, wiper: 0, frost: 0, seed: 9,
		} ),
	P( 'glass-lamp', 'Headlamp Lens (PC + Hardcoat)', 'glass', 'glass',
		'3 mm polycarbonate with a UV hardcoat. Higher dispersion, micro-scratched.',
		{
			tintColor: '#eef4f6', edgeColor: '#cfe0e6', tint: 0.12, transmission: 1,
			roughness: 0.018, ior: 1.586, thickness: 0.003, dispersion: 3.2,
			absorption: 1.1, coating: 0.7, coatThickness: 340,
			scratch: 0.3, wiper: 0, frost: 0.04, seed: 15,
		} ),
	P( 'glass-frosted', 'Frosted / Etched Glass', 'glass', 'glass',
		'Acid-etched diffuser lens.',
		{
			tintColor: '#e8eef0', edgeColor: '#c9d6da', tint: 0.25, transmission: 1,
			roughness: 0.35, ior: 1.5, thickness: 0.004, dispersion: 0.4,
			absorption: 1.5, coating: 0, coatThickness: 200,
			scratch: 0.05, wiper: 0, frost: 0.85, seed: 22,
		} ),
	P( 'glass-mirror', 'Rear-View Mirror', 'metal', 'glass',
		'Silvered float glass — modelled as a near-perfect mirror.',
		{
			finish: 'mirror', baseColor: '#dfe3e8', patinaColor: '#8a8f88',
			metallic: 1, roughness: 0.008, brushScale: 200, brushStrength: 0.06,
			brushAngle: 0, aniso: 0, patina: 0.02, heat: 0,
			coatStrength: 0.35, coatRoughness: 0.01, seed: 2,
		} ),

	/* ============================== METALS ============================== */
	P( 'metal-chrome', 'Bright Chrome Trim', 'metal', 'metal',
		'Hexavalent-free decorative chrome over nickel. Roughness ≈ 0.01.',
		{
			finish: 'mirror', baseColor: '#e9ecf1', patinaColor: '#7d7a6a',
			metallic: 1, roughness: 0.011, brushScale: 200, brushStrength: 0.08,
			brushAngle: 0, aniso: 0, patina: 0.02, heat: 0,
			coatStrength: 0, coatRoughness: 0.02, seed: 6,
		} ),
	P( 'metal-brushed-alu', 'Brushed Aluminium', 'metal', 'metal',
		'Linear-grain brushed 6000-series alloy — anisotropic highlight streak.',
		{
			finish: 'brushed', baseColor: '#c7cbd1', patinaColor: '#8d8a7c',
			metallic: 1, roughness: 0.23, brushScale: 420, brushStrength: 0.7,
			brushAngle: 0, aniso: 0.88, patina: 0.04, heat: 0,
			coatStrength: 0, coatRoughness: 0.05, seed: 14,
		} ),
	P( 'metal-machined-face', 'Machined Alloy Face', 'metal', 'metal',
		'Diamond-turned wheel face — concentric grooves catching the light.',
		{
			finish: 'machined', baseColor: '#d6d9dd', patinaColor: '#6f6a5c',
			metallic: 1, roughness: 0.13, brushScale: 300, brushStrength: 0.65,
			brushAngle: 0, aniso: 0.72, patina: 0.03, heat: 0,
			coatStrength: 0.4, coatRoughness: 0.04, seed: 31,
		} ),
	P( 'metal-cast-alloy', 'Cast Alloy Wheel', 'metal', 'metal',
		'As-cast A356 aluminium — orange-peel casting skin, no machining.',
		{
			finish: 'cast', baseColor: '#9ba1a7', patinaColor: '#6d6a5f',
			metallic: 0.95, roughness: 0.44, brushScale: 140, brushStrength: 0.75,
			brushAngle: 0, aniso: 0.12, patina: 0.12, heat: 0,
			coatStrength: 0.25, coatRoughness: 0.18, seed: 40,
		} ),
	P( 'metal-satin-black', 'Satin Black Alloy', 'metal', 'metal',
		'Dark anodised / painted alloy with a fine linear grain.',
		{
			finish: 'brushed', baseColor: '#23262b', patinaColor: '#3a3d42',
			metallic: 0.9, roughness: 0.4, brushScale: 500, brushStrength: 0.4,
			brushAngle: 90, aniso: 0.35, patina: 0.05, heat: 0,
			coatStrength: 0.5, coatRoughness: 0.2, seed: 55,
		} ),
	P( 'metal-bead-titanium', 'Bead-Blasted Titanium', 'metal', 'metal',
		'Isotropic dimpled finish with a light heat tint.',
		{
			finish: 'bead', baseColor: '#b7b1a6', patinaColor: '#8a7f68',
			metallic: 1, roughness: 0.36, brushScale: 300, brushStrength: 0.6,
			brushAngle: 0, aniso: 0, patina: 0.08, heat: 0.28,
			coatStrength: 0, coatRoughness: 0.05, seed: 62,
		} ),
	P( 'metal-exhaust-hot', 'Titanium Exhaust — Blued', 'metal', 'metal',
		'Run-hot titanium: straw through to deep blue oxide interference.',
		{
			finish: 'brushed', baseColor: '#cdc7bb', patinaColor: '#6a6252',
			metallic: 1, roughness: 0.19, brushScale: 260, brushStrength: 0.45,
			brushAngle: 0, aniso: 0.55, patina: 0.04, heat: 0.92,
			coatStrength: 0, coatRoughness: 0.05, seed: 71,
		} ),

	/* ============================== COMPOSITES ============================== */
	P( 'comp-carbon-twill', 'Carbon Fibre 2×2 Twill', 'composite', 'composite',
		'Pre-preg 2×2 twill under a deep gloss clear. ~6.7 mm tow pitch.',
		{
			layup: 'twill', fiberColor: '#0b0c0f', resinColor: '#25282e', sheenColor: '#8a94a1',
			metallic: 0.32, roughness: 0.34, weaveScale: 150, weaveStrength: 0.95,
			filament: 0.62, resin: 0.32, coatStrength: 1, coatRoughness: 0.022,
			orangePeel: 0.1, sheen: 0.72, seed: 13,
		} ),
	P( 'comp-carbon-matte', 'Dry Carbon — Matte', 'composite', 'composite',
		'Autoclave dry carbon with no clear coat; dry fibre sheen.',
		{
			layup: 'plain', fiberColor: '#101114', resinColor: '#1d2025', sheenColor: '#6f7885',
			metallic: 0.2, roughness: 0.58, weaveScale: 190, weaveStrength: 0.8,
			filament: 0.5, resin: 0.2, coatStrength: 0.12, coatRoughness: 0.5,
			orangePeel: 0.05, sheen: 0.45, seed: 26,
		} ),
	P( 'comp-forged', 'Forged Composite', 'composite', 'composite',
		'Randomly oriented chopped fibre in resin — the "marbled" Lamborghini look.',
		{
			layup: 'forged', fiberColor: '#0d0e11', resinColor: '#2c3037', sheenColor: '#98a2ae',
			metallic: 0.28, roughness: 0.3, weaveScale: 260, weaveStrength: 0.7,
			filament: 0.3, resin: 0.45, coatStrength: 1, coatRoughness: 0.03,
			orangePeel: 0.12, sheen: 0.4, seed: 38,
		} ),
	P( 'comp-bumper', 'Textured Bumper Polymer', 'composite', 'composite',
		'Unpainted PP/EPDM-T20 with a moulded grain and no clear coat.',
		{
			layup: 'grain', fiberColor: '#22252a', resinColor: '#2c3036', sheenColor: '#5b626b',
			metallic: 0, roughness: 0.62, weaveScale: 340, weaveStrength: 0.5,
			filament: 0, resin: 0.3, coatStrength: 0.02, coatRoughness: 0.55,
			orangePeel: 0.25, sheen: 0.1, seed: 47,
		} ),
	P( 'comp-leather', 'Nappa Leather', 'composite', 'composite',
		'Full-grain nappa — fine pebble grain, soft semi-gloss topcoat.',
		{
			layup: 'grain', fiberColor: '#3b2b23', resinColor: '#4d3a2d', sheenColor: '#b39579',
			metallic: 0, roughness: 0.44, weaveScale: 420, weaveStrength: 0.6,
			filament: 0, resin: 0.25, coatStrength: 0.35, coatRoughness: 0.28,
			orangePeel: 0.18, sheen: 0.18, seed: 58,
		} ),
	P( 'comp-kevlar', 'Aramid Weave', 'composite', 'composite',
		'Golden aramid fabric in clear resin — motorsport interior trim.',
		{
			layup: 'plain', fiberColor: '#7d5f18', resinColor: '#3a3020', sheenColor: '#e6c98a',
			metallic: 0.15, roughness: 0.4, weaveScale: 170, weaveStrength: 0.9,
			filament: 0.55, resin: 0.3, coatStrength: 1, coatRoughness: 0.03,
			orangePeel: 0.1, sheen: 0.6, seed: 66,
		} ),
];

export const PRESET_BY_ID = new Map( MATERIAL_LIBRARY.map( ( m ) => [ m.id, m ] ) );

export function presetsByCategory( cat ) {
	return MATERIAL_LIBRARY.filter( ( m ) => m.category === cat );
}
