import { DESERT_PRESETS, DEFAULT_DESERT } from '../src/plant/desertParams';
const preset = DESERT_PRESETS.find((p) => p.name === 'Golden Barrel')!;
const g = { ...DEFAULT_DESERT, ...preset.desert };
const R = g.bodyRadius, H = g.height;
const depth = Math.max(0.05, 0.35*R);
const sink = Math.max(0, g.sink);
const sGround = sink+depth;
const L = H+sGround;
const spacing = Math.max(0.008, g.areoleSpacing);
const tipMargin = Math.max(0.004, spacing*0.3);
const sTop = L - tipMargin;
console.log('L',L,'sTop',sTop, 'gap to tip', L-sTop);
