/* ============================================================
 * Frontier · SDF terrain — exporters
 *
 * Everything an engine needs to consume the generated terrain, and
 * everything needed to reproduce it:
 *
 *   · raw SDF volume  — the `.frontier` container (magic + JSON header +
 *     float32 XYZ grid). Channels: signedDistance, moisture,
 *     depositedSediment, solidFraction. This is the format the engine
 *     should ingest when it wants to keep the terrain implicit (raycast
 *     against it, sculpt it, cut CSG at runtime). It is version 2 of the
 *     format used by the earlier projects, so existing loaders work.
 *   · OBJ + MTL       — the extracted surface, with UVs and 5 material
 *     groups written as faces tagged by dominant layer (`usemtl`).
 *   · STL (binary)    — for DCC tools / printing.
 *   · heightmap PNG   — 16-bit grayscale, plus the channel stack (slope,
 *     flow, erosion, deposit, wetness, curvature) as separate PNGs.
 *   · splatmap PNG    — 5 weighted layers, ready for a terrain shader.
 *   · recipe JSON     — every parameter, so the terrain can be rebuilt
 *     bit-identically (`node tools/generate.mjs --recipe r.json`).
 * ============================================================ */

import { grayToPNG, encodePNG } from './png-lite.js';

const ENCODER = new TextEncoder();

/* ------------------------------ SDF volume ------------------------------ */

/**
 * `.frontier` container: uint32 magic "FSDF", uint32 header length,
 * UTF-8 JSON header, then raw float32 voxels in (z,y,x) order with
 * 4 interleaved channels.
 *
 * @param {import('../core/sdf-volume.js').SdfVolume} vol
 * @param {object} o { params, stats, iterations, camera, extra }
 */
export function encodeSdfVolume(vol, o = {}) {
  const { nx, ny, nz } = vol;
  const count = nx * ny * nz;
  const data = new Float32Array(count * 4);
  const moist = o.moisture || null;
  const deposit = o.depositedSediment || null;
  for (let i = 0; i < count; i++) {
    data[i * 4] = vol.data[i];
    data[i * 4 + 1] = moist ? moist[i] : 0;
    data[i * 4 + 2] = deposit ? deposit[i] : 0;
    data[i * 4 + 3] = vol.data[i] < 0 ? 1 : 0;      // solid fraction
  }
  const header = {
    format: 'frontier-sdf',
    version: 2,
    dimensions: [nx, ny, nz],
    bounds: { min: vol.min, max: vol.max },
    cell: vol.cell,
    channels: ['signedDistance', 'moisture', 'depositedSediment', 'solidFraction'],
    componentType: 'float32',
    byteOrder: 'little-endian',
    layout: 'x-fastest, then y, then z; 4 interleaved channels per voxel',
    erosionModel: 'sdf-macro-fluvial+guarded-particles+v3',
    settings: o.params || null,
    stats: o.stats || null,
    iterations: o.iterations ?? null,
    camera: o.camera || null,
    terrain: o.terrain || null,
    particleStateIncluded: false,
    materialLayersIncluded: Boolean(deposit),
    ...(o.extra || {}),
  };
  const json = ENCODER.encode(JSON.stringify(header));
  const prefix = new Uint32Array([0x46445346 /* FSDF */, json.length]);
  const out = new Uint8Array(8 + json.length + data.byteLength);
  out.set(new Uint8Array(prefix.buffer), 0);
  out.set(json, 8);
  out.set(new Uint8Array(data.buffer), 8 + json.length);
  return out;
}

/** Decode a `.frontier` volume back into a plain grid (used by tests). */
export function decodeSdfVolume(bytes) {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const magic = view.getUint32(0, true);
  if (magic !== 0x46445346) throw new Error('not a frontier-sdf volume');
  const headerLen = view.getUint32(4, true);
  const header = JSON.parse(new TextDecoder().decode(new Uint8Array(bytes.buffer, bytes.byteOffset + 8, headerLen)));
  const [nx, ny, nz] = header.dimensions;
  const count = nx * ny * nz;
  const floats = new Float32Array(count * 4);
  const off = bytes.byteOffset + 8 + headerLen;
  new Uint8Array(floats.buffer).set(bytes.subarray(off, off + floats.byteLength));
  return { header, nx, ny, nz, floats };
}

/* --------------------------------- OBJ --------------------------------- */

/**
 * @param {Array<{positions:Float32Array, normals:Float32Array, indices:Uint32Array, splats?:Float32Array}>} chunks
 * @param {{name?:string, scale?:number}} opt
 */
export function encodeOBJ(chunks, { name = 'frontier', scale = 1, splats = true } = {}) {
  const lines = [`# Frontier SDF terrain — ${name}`, '# generated by frontier/src/io/exporters.js'];
  const layers = ['grass', 'dirt', 'rock', 'sand', 'snow'];
  for (let li = 0; li < layers.length; li++) {
    lines.push(`usemtl ${layers[li]}`);
  }
  let vOff = 1, nOff = 1, tOff = 1;
  let vi = 0;
  for (const c of chunks) {
    const { positions, normals, indices, uvs } = c;
    const nv = positions.length / 3;
    for (let i = 0; i < nv; i++) {
      lines.push(`v ${(positions[i * 3] * scale).toFixed(4)} ${(positions[i * 3 + 1] * scale).toFixed(4)} ${(positions[i * 3 + 2] * scale).toFixed(4)}`);
    }
    for (let i = 0; i < nv; i++) {
      lines.push(`vn ${normals[i * 3].toFixed(4)} ${normals[i * 3 + 1].toFixed(4)} ${normals[i * 3 + 2].toFixed(4)}`);
    }
    if (uvs) {
      for (let i = 0; i < nv; i++) lines.push(`vt ${uvs[i * 2].toFixed(5)} ${uvs[i * 2 + 1].toFixed(5)}`);
    }
    // group triangles by dominant material layer so DCC tools see the split
    const buckets = [[], [], [], [], []];
    for (let t = 0; t < indices.length; t += 3) {
      let best = 0, bestW = -1;
      if (splats && c.splats) {
        for (let l = 0; l < 5; l++) {
          const w = (c.splats[indices[t] * 5 + l] + c.splats[indices[t + 1] * 5 + l] + c.splats[indices[t + 2] * 5 + l]) / 3;
          if (w > bestW) { bestW = w; best = l; }
        }
      }
      buckets[best].push(t);
    }
    void vi;
    for (let l = 0; l < 5; l++) {
      if (!buckets[l].length) continue;
      lines.push(`usemtl ${layers[l]}`);
      for (const t of buckets[l]) {
        const a = indices[t] + vOff, b = indices[t + 1] + vOff, cc = indices[t + 2] + vOff;
        const na = indices[t] + nOff, nb = indices[t + 1] + nOff, nc = indices[t + 2] + nOff;
        if (uvs) {
          const ta = indices[t] + tOff, tb = indices[t + 1] + tOff, tc = indices[t + 2] + tOff;
          lines.push(`f ${a}/${ta}/${na} ${b}/${tb}/${nb} ${cc}/${tc}/${nc}`);
        } else {
          lines.push(`f ${a}//${na} ${b}//${nb} ${cc}//${nc}`);
        }
      }
    }
    vOff += nv; nOff += nv; tOff += nv;
    vi += nv;
  }
  return ENCODER.encode(lines.join('\n') + '\n');
}

export function encodeMTL(name = 'frontier') {
  const defs = [
    ['grass', '0.36 0.44 0.25', '0.60 0.55 0.42'],
    ['dirt', '0.42 0.35 0.26', '0.15 0.12 0.10'],
    ['rock', '0.46 0.46 0.49', '0.42 0.42 0.44'],
    ['sand', '0.76 0.71 0.55', '0.30 0.28 0.22'],
    ['snow', '0.93 0.95 0.98', '0.28 0.30 0.34'],
  ];
  const out = [`# Frontier terrain materials (${name})`];
  for (const [n, kd, ks] of defs) {
    out.push(`newmtl ${n}`, `Kd ${kd}`, `Ks ${ks}`, 'Ns 12', 'illum 2', '');
  }
  return ENCODER.encode(out.join('\n'));
}

/* --------------------------------- STL --------------------------------- */

export function encodeSTL(chunks, { name = 'frontier' } = {}) {
  let tris = 0;
  for (const c of chunks) tris += c.indices.length / 3;
  const buf = new ArrayBuffer(84 + tris * 50);
  const view = new DataView(buf);
  const header = ENCODER.encode(`Frontier SDF terrain ${name} — binary STL`);
  new Uint8Array(buf, 0, 80).set(header.subarray(0, 80));
  view.setUint32(80, tris, true);
  let off = 84;
  const P = (c, i, k) => c.positions[c.indices[i] * 3 + k];
  for (const c of chunks) {
    for (let t = 0; t < c.indices.length; t += 3) {
      const ax = P(c, t, 0), ay = P(c, t, 1), az = P(c, t, 2);
      const bx = P(c, t + 1, 0), by = P(c, t + 1, 1), bz = P(c, t + 1, 2);
      const cx = P(c, t + 2, 0), cy = P(c, t + 2, 1), cz = P(c, t + 2, 2);
      const ux = bx - ax, uy = by - ay, uz = bz - az;
      const vx = cx - ax, vy = cy - ay, vz = cz - az;
      let nx = uy * vz - uz * vy, ny = uz * vx - ux * vz, nz = ux * vy - uy * vx;
      const len = Math.hypot(nx, ny, nz) || 1;
      view.setFloat32(off, nx / len, true); view.setFloat32(off + 4, ny / len, true);
      view.setFloat32(off + 8, nz / len, true);
      for (const [px, py, pz] of [[ax, ay, az], [bx, by, bz], [cx, cy, cz]]) {
        view.setFloat32(off + 12, px, true);
        view.setFloat32(off + 16, py, true);
        view.setFloat32(off + 20, pz, true);
        off += 12;
      }
      view.setUint16(off, 0, true);
      off += 2;
    }
  }
  return new Uint8Array(buf);
}

/* ------------------------------ heightmaps ------------------------------ */

/** 16-bit grayscale PNG of a scalar field (terrain height, in metres). */
export function encodeHeightPNG(hf, { min = null, max = null, verticalScale = 1 } = {}) {
  const { nx, nz, h } = hf;
  let mn = min, mx = max;
  if (mn === null || mx === null) {
    mn = Infinity; mx = -Infinity;
    for (let i = 0; i < h.length; i++) { if (h[i] < mn) mn = h[i]; if (h[i] > mx) mx = h[i]; }
  }
  const span = Math.max(mx - mn, 1e-6);
  const raw = new Uint8Array(nx * nz * 2);
  for (let i = 0; i < nx * nz; i++) {
    let v = ((h[i] - mn) / span) * verticalScale;
    v = v < 0 ? 0 : v > 1 ? 1 : v;
    const q = Math.round(v * 65535);
    // 16-bit PNG expects big-endian samples
    raw[i * 2] = (q >> 8) & 0xff;
    raw[i * 2 + 1] = q & 0xff;
  }
  return encodePNG16(nx, nz, raw);
}

/** 8-bit grayscale PNG of any 0..1 channel. */
export function encodeChannelPNG(field, w, h) {
  let mn = Infinity, mx = -Infinity;
  for (let i = 0; i < field.length; i++) { if (field[i] < mn) mn = field[i]; if (field[i] > mx) mx = field[i]; }
  return grayToPNG(w, h, field, { min: mn, max: mx });
}

/** 5-layer splatmap as an RGB PNG (rock/dirt/grass in R/G/B, sand/snow in an extra pass file). */
export function encodeSplatPNG(weights, w, h) {
  const out = new Uint8Array(w * h * 3);
  for (let i = 0; i < w * h; i++) {
    out[i * 3] = clamp255(weights[i * 5 + 2] * 255);       // rock
    out[i * 3 + 1] = clamp255(weights[i * 5 + 1] * 255);   // dirt
    out[i * 3 + 2] = clamp255(weights[i * 5] * 255);       // grass
  }
  return encodePNG(w, h, out, 3);
}

export function encodeSplatExtraPNG(weights, w, h) {
  const out = new Uint8Array(w * h * 3);
  for (let i = 0; i < w * h; i++) {
    out[i * 3] = clamp255(weights[i * 5 + 3] * 255);       // sand
    out[i * 3 + 1] = clamp255(weights[i * 5 + 4] * 255);   // snow
    out[i * 3 + 2] = 0;
  }
  return encodePNG(w, h, out, 3);
}

/** Coloured preview of the weathered surface (used for thumbnails / docs). */
export function encodeColorPNG(colors, w, h) {
  const out = new Uint8Array(w * h * 3);
  for (let i = 0; i < colors.length; i++) out[i] = clamp255(colors[i] * 255);
  return encodePNG(w, h, out, 3);
}

/* -------------------------------- recipe -------------------------------- */

export function encodeRecipe(params, stats = null) {
  return ENCODER.encode(JSON.stringify({
    format: 'frontier-recipe',
    version: 1,
    generator: 'frontier-terrain',
    params,
    stats,
    created: new Date().toISOString(),
  }, null, 2));
}

const clamp255 = (v) => (v < 0 ? 0 : v > 255 ? 255 : v | 0);

/** Minimal 16-bit grayscale PNG writer (the lite writer is 8-bit). */
function encodePNG16(width, height, samples) {
  // Reuse the 8-bit path with a 16-bit IHDR by handing depth=16 to the encoder.
  return encodePNG(width, height, samples, 1, { bitDepth: 16 });
}
