import '@fontsource/dm-sans/latin-400.css';
import '@fontsource/dm-sans/latin-500.css';
import '@fontsource/dm-sans/latin-600.css';
import '@fontsource/ibm-plex-mono/latin-400.css';
import './style.css';
import {createIcons, Aperture, ArrowUpRight, Box, ChevronDown, ChevronRight, CircleHelp, Code2, Copy, Download, Expand, Focus, Github, Layers3, Lightbulb, Maximize2, MoreHorizontal, Move3d, Orbit, Pause, Play, Plus, RotateCcw, Settings2, SlidersHorizontal, Sparkles, Triangle, X, Zap, Check, Monitor, Activity, Sun, Grid3x3, BookOpen, Camera} from 'lucide';
import {settings,updateScene,makeScene,sceneInfo} from './scene.js';
import {GPURenderer} from './gpu.js';
import {FallbackRenderer} from './fallback.js';
import {runBenchmark} from './benchmark.js';
import {getProbeConfig} from './probes.js';
const icon=(name,cls='')=>`<i data-lucide="${name}" class="${cls}"></i>`;
const toggle=(id,on=true)=>`<button class="switch ${on?'on':''}" id="${id}" role="switch" aria-checked="${on}" aria-label="${id.replaceAll('-',' ')}"><span></span></button>`;
document.querySelector('#app').innerHTML=`
<header class="topbar"><a class="brand" href="./index.html" aria-label="Cascade lab home"><span class="brand-icon">${icon('layers-3')}</span>cascade<span class="brand-suffix">/ lab</span><span class="version">v0.7</span></a><nav aria-label="Main navigation"><button class="nav active" data-nav="playground">Playground</button><button class="nav" data-nav="technique">The technique ${icon('arrow-up-right')}</button><button class="nav" data-nav="integration">Integration ${icon('arrow-up-right')}</button></nav><button class="source-button" id="source">${icon('code-2')} Renderer notes ${icon('arrow-up-right')}</button></header>
<main>
<section class="page-heading"><div><div class="eyebrow"><span class="tiny-dot"></span> REAL-TIME GLOBAL ILLUMINATION</div><h1>Light, without the wait<span>.</span></h1><p>Explore 3D radiance cascades. Dynamic geometry. Every frame.</p></div><div class="heading-right"><div class="engine-pill"><span class="status-dot"></span><span id="engine-status">Initializing WebGPU</span></div><span class="experimental">EXPERIMENTAL RENDERER</span></div></section>
<div class="workspace">
<aside class="controls"><div class="panel-heading">${icon('sliders-horizontal')} <h2>Scene controls</h2><button class="icon-button" id="reset" aria-label="Reset all settings" title="Reset all settings">${icon('rotate-ccw')}</button></div>
<div class="control-section"><label class="section-label" for="scene-select">SCENE</label><div class="select-wrap">${icon('box')}<select id="scene-select">${Object.entries(sceneInfo).map(([key,value])=>`<option value="${key}">${value[0]}</option>`).join('')}</select>${icon('chevron-down')}</div><div class="scene-description">${sceneInfo.chamber[1]}</div><div class="scene-tags"><span>3D WORLD</span><span>DYNAMIC</span></div><div id="deform-controls" hidden><div class="range-label"><label for="wave-amplitude">Vertex displacement</label><output id="wave-amplitude-value">1.00<span>×</span></output></div><input id="wave-amplitude" type="range" min="0" max="1.5" step=".05" value="1"><p class="control-help">Connected indexed mesh · 1,617 vertices · 3,072 triangles. The top edge is pinned. Set displacement to zero for a flat sheet.</p></div><div id="large-controls" hidden><div class="range-label"><label for="large-count">Crate density</label><output id="large-count-value">500</output></div><input id="large-count" type="range" min="0" max="1000" step="25" value="500"><p class="control-help" id="large-count-help">10,008 triangles · 24 × 22 × 10 m. Release the slider to rebuild.</p></div><div id="stress-controls" hidden><div class="resolution-control"><label for="stress-count">Mesh instances</label><select id="stress-count"><option value="64">64</option><option value="256" selected>256</option><option value="768">768</option><option value="1536">1,536</option></select></div><p class="control-help">12 triangles per cube. A CPU-refitted BVH handles the moving triangle field.</p></div></div>
<div class="control-section"><div class="section-title"><span class="section-label">RADIANCE CASCADES</span><span class="tiny-badge">GI</span></div><div class="range-label"><label for="probe-density">Spatial probe density</label><output id="probe-density-value">990</output></div><input id="probe-density" type="range" min="0" max="3" step="1" value="1"><div class="range-ends"><span>Low</span><span>Ultra</span></div><div class="range-label"><label for="probe-angular">Angular detail</label><output id="probe-angular-value">16 / 64 / 256</output></div><input id="probe-angular" type="range" min="0" max="1" step="1" value="0"><p class="control-help" id="probe-budget">25,344 interval rays per update.</p><div class="control-row"><label for="probe-visibility">Visibility-aware GI</label>${toggle('probe-visibility',true)}</div><p class="control-help">Always checks probe validity, cascade endpoint connections and surface-to-probe visibility. Conservative filtering may darken difficult corners.</p><div class="control-row"><label for="temporal">Temporal reconstruction</label>${toggle('temporal',true)}</div><div class="control-row"><label for="spatial-filter">Edge-aware filter</label>${toggle('spatial-filter',true)}</div><div class="resolution-control"><label for="probe-update-budget">Probe update budget</label><select id="probe-update-budget"><option value="1">All / frame</option><option value="2">Half / frame</option><option value="4" selected>Quarter / frame</option></select></div><p class="control-help">Changed regions get priority within the budget. Resets refresh all probes. Reconstruction uses up to 8 fresh direct-light samples per emitter; disabling it uses your full sample settings and updates every probe.</p><div class="control-row"><label for="enable-gi">Global illumination</label>${toggle('enable-gi')}</div><div class="range-label"><label for="bounce">Indirect intensity</label><output id="bounce-value">1.00<span>×</span></output></div><input id="bounce" type="range" min="0" max="2" step=".05" value="1"><div class="range-ends"><span>Subtle</span><span>Amplified</span></div><div class="static-control"><span>Cascade levels</span><span class="step-count">3 <span>levels</span> ${icon('layers-3')}</span></div><div class="cascade-scale"><span>C0</span><span>C1</span><span>C2</span></div><div class="cascade-hint">Near-field detail → far-field coverage</div></div>
<div class="control-section"><span class="section-label">LIGHT & MOTION</span><div class="range-label"><label for="emission">Emission strength</label><output id="emission-value">2.8<span>×</span></output></div><input id="emission" type="range" min=".2" max="6" step=".1" value="2.8"><div class="range-label"><label for="emitter-size">Area emitter size</label><output id="emitter-size-value">1.0<span>×</span></output></div><input id="emitter-size" type="range" min=".15" max="2" step=".05" value="1"><div class="resolution-control"><label for="shadow-samples">Panel sample target</label><select id="shadow-samples"><option value="1">1 · hard</option><option value="4" selected>4 · fast</option><option value="16">16 · soft</option><option value="64">64 · smooth</option></select></div><div class="range-label"><label for="orb-power">Orb emission</label><output id="orb-power-value">1.0<span>×</span></output></div><input id="orb-power" type="range" min="0" max="5" step=".1" value="1"><div class="resolution-control"><label for="orb-samples">Orb sample target</label><select id="orb-samples"><option value="8">8 · fast</option><option value="16" selected>16 · balanced</option><option value="32">32 · quality</option><option value="64">64 · fine</option></select></div><div class="control-row"><label for="orb-only">Isolate emissive ball</label>${toggle('orb-only',false)}</div><p class="control-help">Mesh light emits in all directions; brightness falls with distance. No visible fog or hard cutoff radius. Orb samples affect direct/reflected shading; cascade hits use up to 4.</p><div class="light-swatches"><span><b class="warm-dot"></b>Warm emitter</span><span><b class="cool-dot"></b>Cool emitter</span></div><div class="control-row motion-row"><label for="animate">Animate geometry</label>${toggle('animate')}</div><div class="range-label"><label for="speed">Animation speed</label><output id="speed-value">1.0<span>×</span></output></div><input id="speed" type="range" min=".1" max="2" step=".1" value="1"></div>
<div class="control-section debug-section"><span class="section-label">VISUALIZATION</span><div class="control-row"><label for="show-probes">Probe overlay</label>${toggle('show-probes',true)}</div><div class="resolution-control"><label for="probe-level">Probe level</label><select id="probe-level"><option value="0">C0 · 864</option><option value="1" selected>C1 · 108</option><option value="2">C2 · 18</option></select></div><div class="resolution-control"><label for="probe-mode">Probe colors</label><select id="probe-mode"><option value="0">Radiance</option><option value="1">Cascade ID</option><option value="2">Visibility</option></select></div><p class="control-help">X-ray probe markers. Radiance = average merged light; visibility = interval miss fraction.</p><div class="control-row"><label for="wireframe">Triangle edges / wireframe</label>${toggle('wireframe',false)}</div><div class="resolution-control"><label for="resolution">Render scale</label><select id="resolution"><option value=".5">50%</option><option value=".75" selected>75%</option><option value="1">100%</option></select></div></div>
<div class="control-section acceleration-section"><span class="section-label">RAY TRACING</span><div class="control-row"><label for="bvh">Triangle BVH</label>${toggle('bvh')}</div><div class="control-row"><label for="reflections">Traced reflections</label>${toggle('reflections')}</div><p class="control-help">One reflected ray per reflective hit. Every object is triangles, including the emitters. No SDF or analytic surface tests; no SSR.</p></div><div class="controls-footer">${icon('info')}<span>All geometry and lighting update live.</span></div></aside>
<section class="renderer-panel" aria-label="Interactive 3D renderer"><div class="viewport-toolbar"><div class="view-tabs" role="tablist" aria-label="Render view"><button class="view-tab active" data-view="0" role="tab" aria-selected="true">${icon('box')} Lit</button><button class="view-tab" data-view="1" role="tab" aria-selected="false">Direct only</button><button class="view-tab" data-view="2" role="tab" aria-selected="false">Indirect</button><button class="view-tab" data-view="3" role="tab" aria-selected="false">Normals</button><button class="view-tab" data-view="4" role="tab" aria-selected="false">Probe atlas</button></div><div class="viewport-actions"><button class="icon-button" id="snapshot" aria-label="Download viewport image" title="Save image">${icon('camera')}</button><span></span><button class="icon-button" id="fullscreen" aria-label="Expand viewport" title="Fullscreen">${icon('maximize-2')}</button></div></div>
<div class="trace-comparison"><div><strong id="trace-mode">Raster visibility + BVH lighting</strong><span id="trace-cost">Refit bounds, then skip whole triangle groups.</span></div><label for="bvh-quick">BVH acceleration</label>${toggle('bvh-quick')}<button id="benchmark" class="benchmark-button">Measure A/B</button></div><div class="viewport" id="viewport"><canvas id="scene-canvas" aria-label="3D light chamber with animated geometry"></canvas><div class="viewport-title"><span class="live-tag"><b></b> LIVE</span><span id="scene-title">THE LIGHT CHAMBER</span></div><div class="viewport-top-right"><span id="render-api">WEBGPU</span><span class="quality-label">REAL-TIME</span></div><div class="loading" id="loading"><div class="loader-orbit"></div><span>Building the light field</span><small>Initializing renderer & shaders</small></div><div class="probe-legend" id="probe-legend"></div><div class="viewport-bottom-left"><div class="axis-widget"><span class="axis-y">Y</span><span class="axis-z">Z</span><span class="axis-x">X</span><i></i></div><span class="perspective-label">PERSPECTIVE</span></div><div class="viewport-hint">${icon('orbit')} Drag to orbit <span>·</span> Scroll to zoom</div><button class="reset-camera" id="reset-camera" aria-label="Reset camera" title="Reset camera">${icon('focus')}</button><div class="fallback-notice" id="fallback-notice" hidden>WebGL preview <span>·</span> WebGPU needed for cascades ${icon('circle-help')}</div></div>
<div class="playback-bar"><button class="play-button" id="play" aria-label="Pause animation">${icon('pause')}</button><div class="playback-state"><span id="playback-state">Simulation running</span><span><b class="small-dot"></b> Dynamic triangles</span></div><div class="waveform" aria-hidden="true">${Array.from({length:42},(_,i)=>`<i style="--h:${6+Math.sin(i*.7)**2*14}px;--d:${i*.035}s"></i>`).join('')}</div><span class="timecode" id="timecode">00:00.00</span><button class="icon-button" id="restart" aria-label="Restart simulation" title="Restart simulation">${icon('rotate-ccw')}</button><div class="playback-divider"></div><span class="frame-tag">FRAME <span id="frame-count">0000</span></span></div>
<div class="metrics"><div class="metric"><div class="metric-label">${icon('activity')} FRAME RATE</div><div class="metric-value"><span id="fps">—</span><small>fps</small><span class="metric-sparkline"></span></div></div><div class="metric"><div class="metric-label">${icon('zap')} GPU TIME</div><div class="metric-value"><span id="gpu-time">—</span><small>ms</small><span class="metric-detail" id="timing-label">GPU stages</span></div></div><div class="metric"><div class="metric-label">${icon('grid-3x3')} RADIANCE PROBES</div><div class="metric-value"><span id="probe-count">990</span><span class="metric-detail" id="probe-detail">across 3 cascades</span></div></div><div class="metric"><div class="metric-label">${icon('triangle')} SCENE GEOMETRY</div><div class="metric-value"><span id="triangle-count">—</span><small>tris</small><span class="dynamic-tag">DYNAMIC</span></div></div></div>
<div class="pass-timings" aria-label="GPU pass times"><span>Visibility raster <b id="visibility-ms">—</b> ms</span><span>Cascades + gather <b id="cascade-ms">—</b> ms</span><span>Lighting + shadows + reflection <b id="shading-ms">—</b> ms</span><span>Reconstruction <b id="reconstruction-ms">—</b> ms</span><span>Present + overlay <b id="present-ms">—</b> ms</span></div><div class="frame-breakdown" id="frame-breakdown">Scene update · CPU preparation · encode · submit-to-complete · completed render</div><div class="telemetry"><button class="telemetry-item" id="memory-info" title="What this memory estimate includes"><span>VRAM ALLOCATION · EST.</span><strong><b id="vram">—</b> <small>MiB</small> ${icon('circle-help')}</strong></button><div class="telemetry-item"><span>ACCELERATION</span><strong id="bvh-status">BVH · refit</strong></div><div class="telemetry-item"><span>MESH OBJECTS</span><strong id="mesh-count">—</strong></div><div class="telemetry-item"><span>CPU PACK + BVH</span><strong><b id="cpu-time">—</b> <small>ms</small></strong></div></div>
</section></div>
<section class="scene-library"><div class="library-title"><span class="section-label">EXPLORE THE TEST SCENES</span><span>Same renderer. Different challenges.</span></div><div class="scene-buttons">${Object.entries(sceneInfo).map(([key,value],i)=>`<button data-scene="${key}" class="scene-card ${key==='chamber'?'selected':''}"><span class="scene-number">0${i+1}</span>${icon(['box','move-3d','sun','orbit','expand','grid-3x3','triangle','layers-3'][i])}<strong>${value[0]}</strong><span>${['Color bleed & motion','3,072 connected triangles','Area light & penumbra','All-triangle geometry','10,008 tris · 24 m room','Up to 18,432 cube tris','64 deforming triangles','Occlusion & reflections'][i]}</span></button>`).join('')}</div></section>
<section class="bottom-strip"><div class="experiment-note"><span class="note-icon">${icon('sparkles')}</span><div><h3>A small scene. A bigger possibility.</h3><p>No lightmaps. No baking. Just light that keeps up with your world.</p></div></div><button id="how-it-works">How radiance cascades work ${icon('arrow-up-right')}</button></section>
<footer><span><b class="footer-dot"></b> Built for the next frame.</span><div>3D radiance cascades <span>/</span> WebGPU <span>/</span> Open experiment</div><button id="shortcuts">${icon('command')} Keyboard shortcuts</button></footer>
</main><dialog id="info-dialog"><button class="dialog-close icon-button" aria-label="Close dialog">${icon('x')}</button><div id="dialog-content"></div></dialog><div id="toast" role="status"></div>`;
// Keep icon registration explicit for a small, tree-shakeable bundle.
import {Info,Command} from 'lucide';
const icons={Aperture,ArrowUpRight,Box,ChevronDown,ChevronRight,CircleHelp,Code2,Copy,Download,Expand,Focus,Github,Layers3,Lightbulb,Maximize2,MoreHorizontal,Move3d,Orbit,Pause,Play,Plus,RotateCcw,Settings2,SlidersHorizontal,Sparkles,Triangle,X,Zap,Check,Monitor,Activity,Sun,Grid3x3,BookOpen,Camera,Info,Command};
const refreshIcons=()=>createIcons({icons});refreshIcons();
const $=s=>document.querySelector(s);
const dialog=$('#info-dialog');
const technique=()=>{const config=getProbeConfig();return `<div class="eyebrow">THE TECHNIQUE</div><h2>More reach.<br>Less redundant work.</h2><p>Radiance cascades trade spatial detail for angular detail. Nearby light is sampled on a dense probe grid; distant light uses fewer probes with more ray directions.</p><div class="level-cards">${config.counts.map((n,i)=>`<div><b>C${i}</b><strong>${n.toLocaleString()} probes</strong><span>${config.sides[i]**2} directions · ${i?config.intervals[i-1].toFixed(1):0}–${config.intervals[i].toFixed(1)} m</span></div>`).join('')}</div><h3>What actually runs here</h3><p>Changed mesh vertices and instance transforms are uploaded; shared/static meshes stay cached. A full refresh traces ${config.totalRays.toLocaleString()} interval rays; budgeted frames trace a subset from far to near, merging unoccluded radiance from the next cascade. Six directional irradiance lobes are gathered per near-field probe and trilinearly sampled for shading.</p><h3>An experiment, not a solved renderer</h3><p>This prototype uses shared local mesh BLASes and an object TLAS; triangle meshes for all spheres, boxes and capsules; approximate spatial merging; and direct lighting at ray hits. It uses temporal reconstruction and conservative visibility-tested merging, but not full multi-bounce transport. Samples can lag or darken near difficult occlusion. Expect light leaks, probe bias, and device-dependent frame rates. “Indirect” shows estimated reflected light plus the unregistered sky backdrop. Registered lamps are sampled by direct lighting and excluded from the probe field to avoid double-counting. Coarse merging still leaks and aliases; soft direct shadows do not validate the GI result.</p>`;};
const integration=`<div class="eyebrow">ENGINE INTEGRATION</div><h2>From the lab<br>to your game.</h2><p>This is a working WebGPU research prototype, not a drop-in production GI solution. The rendering stages are separated so you can experiment with your own engine.</p><ol class="integration-list"><li><b>Upload the world</b><span><code>src/acceleration.js</code> caches local mesh BLASes and updates instance transforms and a TLAS. Vertex deformation refits only its mesh; unchanged geometry stays cached. External geometry changes must update attribute versions.</span></li><li><b>Trace & merge</b><span><code>src/modern-shaders.js</code> performs visibility rasterization, budgeted interval tracing, visibility-tested merging and reconstruction.</span></li><li><b>Light the frame</b><span><code>src/gpu.js</code> schedules compute dispatches, updates storage buffers, and presents the final image.</span></li></ol><h3>Before shipping</h3><p>Improve hierarchy quality and probe placement, add object motion vectors/GPU refits, and integrate engine materials. The current conservative merging and history rejection remain approximate. Measure on your target GPU. The FPS counter measures the browser frame loop; GPU time uses hardware timestamp queries when available.</p><div class="dialog-callout">Requires WebGPU over HTTPS or localhost. The WebGL fallback is only a raster preview and does not execute radiance cascades.</div>`;
const rendererNotes=`<div class="eyebrow">RENDERER v0.7</div><h2>Visibility first.<br>Trace the lighting.</h2><p>A depth-tested visibility raster stores instance and triangle IDs. Exact pixel-centre barycentrics are reconstructed from that selected triangle. Shading reconstructs the visible mesh surface without tracing a primary camera ray.</p><h3>Shared geometry</h3><p>Each unique mesh owns a local triangle BLAS. Instances share it; a TLAS bounds the objects. Only changed vertex meshes refit their BLAS. Static mesh data stays on the GPU. Bounding boxes only cull: every light/reflection/visibility hit is a triangle.</p><h3>Conservative GI</h3><p>Opposing backface tests reject enclosed probes. Cascade merging samples spatial neighbours and finer angular bins over time and tests the segment joining displaced interval endpoints. Surface-to-probe visibility is mandatory. Blocked or invalid samples contribute zero, so some corners can be too dark. This is not a complete physical transport solution.</p><h3>Reconstruction and budgets</h3><p>Quarter/half/all probe updates use an age-bounded scheduler that prioritizes changed regions. Initial frames and setting changes refresh everything. Frozen fields stop updating after convergence warm-up. Camera reprojection rejects mismatched surfaces, moved instances, normal/depth changes and view-dependent reflections during camera motion. Lighting/settings changes reset history; moving scenes use shorter history. A geometry-aware neighbourhood clamps history, and a separate filter rejects cross-object and cross-normal samples.</p><h3>Measurements</h3><p>CPU scene update, preparation, encoding, submission wait and completed-render wall time are shown separately. GPU visibility, cascades, shading, reconstruction and presentation have separate timestamps. Submission wait contains GPU execution: do not add it to GPU time. No target-device FPS improvement is assumed.</p>`;
function openInfo(content){$('#dialog-content').innerHTML=content;dialog.showModal();}
$('[data-nav="technique"]').onclick=()=>openInfo(technique());$('[data-nav="integration"]').onclick=()=>openInfo(integration);$('#source').onclick=()=>openInfo(rendererNotes);$('#how-it-works').onclick=()=>openInfo(technique());$('.dialog-close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close();};
$('#shortcuts').onclick=()=>openInfo(`<div class="eyebrow">TAKE CONTROL</div><h2>Stay in the flow.</h2><div class="shortcut"><span>Play / pause simulation</span><kbd>Space</kbd></div><div class="shortcut"><span>Reset camera</span><kbd>R</kbd></div><div class="shortcut"><span>Toggle global illumination</span><kbd>G</kbd></div><div class="shortcut"><span>Toggle probe overlay</span><kbd>P</kbd></div><div class="shortcut"><span>Expand viewport</span><kbd>F</kbd></div><div class="shortcut"><span>Orbit / zoom</span><kbd>Drag / Scroll</kbd></div>`);
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
function setToggle(id,value){$(id).classList.toggle('on',value);$(id).setAttribute('aria-checked',String(value));}
function setRunning(v){settings.running=v;setToggle('#animate',v);$('#play').innerHTML=icon(v?'pause':'play');$('#play').setAttribute('aria-label',v?'Pause animation':'Play animation');$('#playback-state').textContent=v?'Simulation running':'Simulation paused';$('.waveform').classList.toggle('paused',!v);refreshIcons();}
$('#animate').onclick=()=>setRunning(!settings.running);$('#play').onclick=()=>setRunning(!settings.running);
for(const [id,key] of [['temporal','temporal'],['spatial-filter','spatialFilter'],['orb-only','orbOnly'],['probe-visibility','probeVisibility'],['enable-gi','gi'],['show-probes','probes'],['wireframe','wireframe'],['bvh','bvh'],['reflections','reflections']])$(`#${id}`).onclick=()=>{if(key==='bvh'&&((settings.scene==='stress'&&settings.stressCount>256)||settings.scene==='large')){toast('Use a smaller scene for brute force; the large hall stays BVH-accelerated.');return;}settings[key]=!settings[key];setToggle(`#${id}`,settings[key]);updateLegend();};
function paintRange(el){el.style.setProperty('--progress',`${(el.value-el.min)/(el.max-el.min)*100}%`);}
for(const [id,key,dec] of [['bounce','bounce',2],['emission','emission',1],['speed','speed',1],['emitter-size','emitterSize',2],['wave-amplitude','waveAmplitude',2],['orb-power','orbPower',1]]){const el=$(`#${id}`);el.oninput=()=>{settings[key]=Number(el.value);$(`#${id}-value`).innerHTML=`${settings[key].toFixed(dec)}<span>×</span>`;paintRange(el);};paintRange(el);}
$('#resolution').onchange=e=>{settings.resolution=Number(e.target.value);};
function syncBVHControls(){
 setToggle('#bvh-quick',settings.bvh);setToggle('#bvh',settings.bvh);
 $('#bvh-quick').disabled=isFallback||benchmarking;$('#bvh').disabled=isFallback||benchmarking;$('#benchmark').disabled=isFallback||benchmarking;for(const id of ['temporal','spatial-filter','probe-update-budget'])$(`#${id}`).disabled=isFallback||benchmarking;$('#probe-visibility').disabled=true;setToggle('#probe-visibility',!isFallback);
 $('#trace-mode').textContent=isFallback?'Raster preview':settings.bvh?'Raster visibility + BVH lighting':'Raster visibility + brute lighting';
 $('#trace-cost').textContent=isFallback?'BVH comparison requires WebGPU.':settings.bvh?`CPU BLAS/TLAS build/refit: ${renderer?.bvhMs?.toFixed(2)??'—'} ms · compare CPU + GPU cost`:'Lighting rays bypass both hierarchies and test instanced mesh triangles. Raster camera visibility is unchanged; hierarchy data remains cached.';
}
$('#bvh-quick').onclick=()=>$('#bvh').click();
function updateLegend(){syncBVHControls();updateProbeUI();const el=$('#probe-legend');el.hidden=!settings.probes&&settings.view!==4;el.textContent=isFallback?'Illustrative probe layout · no cascade data':settings.view===4?`C${settings.probeLevel} DIRECTION ATLAS · ${settings.probeMode===2?'INTERVAL VISIBILITY':'MERGED RADIANCE'}`:`C${settings.probeLevel} · ${getProbeConfig().counts[settings.probeLevel]} PROBES · ${['RADIANCE','CASCADE ID','VISIBILITY'][settings.probeMode]} · X-RAY`;}
function selectScene(key){
 settings.scene=key;const sceneURL=new URL(location.href);sceneURL.searchParams.set('scene',key);history.replaceState(null,'',sceneURL);settings.time=0;frames=0;resetCamera();$('#scene-select').value=key;$('#scene-title').textContent=sceneInfo[key][0].toUpperCase();$('.scene-description').textContent=sceneInfo[key][1];$('#stress-controls').hidden=key!=='stress';$('#deform-controls').hidden=key!=='deform'&&key!=='large';$('#large-controls').hidden=key!=='large';document.querySelectorAll('[data-scene]').forEach(el=>el.classList.toggle('selected',el.dataset.scene===key));
 if(key==='large'){settings.bvh=true;setToggle('#bvh',true);settings.probes=false;setToggle('#show-probes',false);settings.shadowSamples=4;$('#shadow-samples').value='4';}
 if(key==='deform'){settings.probes=false;setToggle('#show-probes',false);settings.shadowSamples=4;$('#shadow-samples').value='4';}
 if(key==='windows'){settings.shadowSamples=16;$('#shadow-samples').value='16';settings.probes=false;setToggle('#show-probes',false);}if(key==='stress'){settings.bvh=true;setToggle('#bvh',true);settings.shadowSamples=1;$('#shadow-samples').value='1';}
 makeScene();updateLegend();toast(`${sceneInfo[key][0]} loaded`);
}
$('#scene-select').onchange=e=>selectScene(e.target.value);
for(const el of document.querySelectorAll('[data-scene]'))el.onclick=()=>selectScene(el.dataset.scene);
$('#stress-count').onchange=e=>{settings.stressCount=Number(e.target.value);if(settings.stressCount>256){settings.bvh=true;setToggle('#bvh',true);}makeScene();toast(`${settings.stressCount.toLocaleString()} dynamic cubes`);};
for(const [id,key] of [['probe-update-budget','probeBudget'],['orb-samples','orbSamples'],['shadow-samples','shadowSamples'],['probe-level','probeLevel'],['probe-mode','probeMode']])$(`#${id}`).onchange=e=>{settings[key]=Number(e.target.value);updateLegend();};
$('#memory-info').onclick=()=>{const m=renderer?.memory;const mib=x=>(x/1048576).toFixed(3);openInfo(`<div class="eyebrow">GPU MEMORY ACCOUNTING</div><h2>Allocated, not total VRAM.</h2><p>WebGPU does not expose total device VRAM, driver memory, or other applications' GPU use. This estimate sums the renderer-owned buffer capacities and visibility/depth, lighting and history textures, plus temporary capture resources while active.</p><div class="shortcut"><span>Allocated buffers</span><kbd>${m?mib(m.buffers)+' MiB':'Unavailable'}</kbd></div><div class="shortcut"><span>Visibility, depth, lighting and history textures</span><kbd>${m?mib(m.textures)+' MiB':'Unavailable'}</kbd></div><div class="shortcut"><span>Owned allocations</span><kbd>${m?mib(m.total)+' MiB':'Unavailable'}</kbd></div><p>Includes padded triangle/BVH capacities, emitter triangles and area tables, cascade fields, irradiance, uniforms, and timing readback buffers. Capacities are retained after reducing scene load. Excludes browser presentation buffers, pipeline/driver overhead, query-set implementation memory, and delayed destruction. WebGL fallback is not estimated.</p>`);};
for(const el of document.querySelectorAll('[data-view]'))el.onclick=()=>{if(isFallback&&Number(el.dataset.view)===4){toast('Probe atlas requires the WebGPU compute path.');return;}settings.view=Number(el.dataset.view);document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b===el);b.setAttribute('aria-selected',String(b===el));});updateLegend();if(isFallback&&settings.view===2)toast('Preview only: WebGL does not calculate cascade irradiance.');};
function updateProbeUI(){
 $('#large-count-value').textContent=settings.largeCount.toLocaleString();$('#large-count-help').textContent=`${(4008+settings.largeCount*12).toLocaleString()} triangles · 24 × 22 × 10 m. Release to rebuild.`;
 const c=getProbeConfig();$('#probe-density-value').textContent=c.totalProbes.toLocaleString();$('#probe-angular-value').textContent=c.sides.map(n=>n*n).join(' / ');
 $('#probe-budget').textContent=`${c.name} · ${c.totalRays.toLocaleString()} interval rays/full refresh · ${c.size.join(' × ')} m coverage. More probes increase memory and GPU work; they do not guarantee correct GI.`;
 for(const [i,option] of [...$('#probe-level').options].entries())option.textContent=`C${i} · ${c.counts[i].toLocaleString()}`;
 $('#probe-count').textContent=isFallback?'—':c.totalProbes.toLocaleString();$('#probe-detail').textContent=isFallback?'WebGPU required':'across 3 cascades';
 for(const id of ['probe-density','probe-angular','large-count'])paintRange($(`#${id}`));
}
for(const [id,key] of [['probe-density','probeDensity'],['probe-angular','probeAngular']])$(`#${id}`).oninput=e=>{settings[key]=Number(e.target.value);updateLegend();};
$('#large-count').oninput=e=>{settings.largeCount=Number(e.target.value);$('#large-count-value').textContent=settings.largeCount.toLocaleString();$('#large-count-help').textContent=`${(4008+settings.largeCount*12).toLocaleString()} triangles · 24 × 22 × 10 m. Release to rebuild.`;paintRange(e.target);};
$('#large-count').onchange=()=>{makeScene();toast(`${(4008+settings.largeCount*12).toLocaleString()} triangles in the grand hall`);};
function resetCamera(){settings.cameraYaw=0;settings.cameraPitch=0;settings.distance=settings.scene==='large'?29.6:14.8;}
$('#reset-camera').onclick=resetCamera;$('#restart').onclick=()=>{settings.time=0;frames=0;};
$('#reset').onclick=()=>{selectScene('chamber');for(const [id,v] of [['bounce',1],['emission',2.8],['speed',1],['emitter-size',1],['wave-amplitude',1],['orb-power',1]]){$(`#${id}`).value=v;$(`#${id}`).oninput();}for(const [id,key,v] of [['temporal','temporal',true],['spatial-filter','spatialFilter',true],['orb-only','orbOnly',false],['probe-visibility','probeVisibility',false],['enable-gi','gi',true],['show-probes','probes',true],['wireframe','wireframe',false],['bvh','bvh',true],['reflections','reflections',true]]){settings[key]=v;setToggle(`#${id}`,v);}settings.resolution=.75;$('#resolution').value='.75';for(const [id,key,v] of [['shadow-samples','shadowSamples',4],['probe-level','probeLevel',1],['probe-mode','probeMode',0],['stress-count','stressCount',256],['probe-update-budget','probeBudget',4],['orb-samples','orbSamples',16],['probe-density','probeDensity',1],['probe-angular','probeAngular',0],['large-count','largeCount',500]]){settings[key]=v;$(`#${id}`).value=String(v);}$('[data-view="0"]').click();setRunning(true);toast('Scene settings restored');};
function downloadJSON(report){const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cascade-benchmark.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);}
$('#benchmark').onclick=()=>{
 if(isFallback||benchmarking)return;
 openInfo(`<div class="eyebrow">MEASURE ON YOUR GPU</div><h2>BVH vs brute force.</h2><p>Freezes the current scene pose, camera and all quality settings. Runs BVH / brute / brute / BVH, with 2 warm-up frames and 8 measured frames per block. Measures CPU preparation, completed-render wall time and separate GPU passes.</p><div class="dialog-callout">Uses your CURRENT resolution and shadow sample count. May temporarily become slow. Stops after 30 seconds or a frame exceeding 2.5 seconds; submitted GPU work cannot be cancelled mid-frame. Keep the tab visible and do not resize it.</div><p>For a lighter run, lower render scale and shadow samples first. This does not measure browser FPS or guarantee a particular game frame rate.</p><button class="benchmark-button" id="run-benchmark">Start measurement</button>`);
 $('#run-benchmark').onclick=async()=>{
  if((settings.scene==='stress'&&settings.stressCount>256)||settings.scene==='large'){toast('Use a smaller scene for brute-force benchmarking. The grand hall is a BVH stress test.');return;}
  benchmarking=true;benchmarkAbort=new AbortController();drag=null;
  const controls=[...document.querySelectorAll('main button, main input, main select, .topbar button')];const disabled=controls.map(el=>el.disabled);controls.forEach(el=>el.disabled=true);
  $('#dialog-content').innerHTML=`<div class="eyebrow">BENCHMARK RUNNING</div><h2>Same scene. Two paths.</h2><p id="benchmark-progress">Waiting for the current frame…</p><p>Animation and controls are temporarily locked. Closing this dialog cancels after the submitted frame finishes.</p><button id="cancel-benchmark" class="benchmark-button">Cancel</button>`;
  $('#cancel-benchmark').onclick=()=>benchmarkAbort.abort();const cancel=()=>benchmarkAbort.abort();dialog.addEventListener('close',cancel);
  let report;
  try{await frameInFlight;await renderer.timingReady;report=await runBenchmark(renderer,{signal:benchmarkAbort.signal,onProgress:p=>{const el=$('#benchmark-progress');if(el)el.textContent=`${p.done}/${p.total} frames · ${p.bvh?'BVH':'brute force'} · ${p.warmup?'warm-up':'measured'} · ${p.wallMs.toFixed(1)} ms completed render`;}});}
  catch(error){toast('Benchmark failed; the GPU may have been interrupted.');console.error(error);}
  finally{dialog.removeEventListener('close',cancel);controls.forEach((el,i)=>el.disabled=disabled[i]);benchmarking=false;last=performance.now();statTime=last;statFrames=0;fpsHistory=[];syncBVHControls();}
  if(!report)return;
  const format=value=>value==null?'—':value.toFixed(2);
  const row=(label,key)=>`<tr><th>${label}</th><td>${format(report.summary.bvh[key]?.median)}</td><td>${format(report.summary.brute[key]?.median)}</td></tr>`;
  openInfo(`<div class="eyebrow">MEASURED ON THIS BROWSER</div><h2>Comparison results.</h2><p>${report.output.width} × ${report.output.height} pixels · ${report.output.triangles.toLocaleString()} triangles · ${report.output.meshObjects} mesh objects</p><p id="benchmark-status"></p><table class="benchmark-table"><thead><tr><th>Median (ms)</th><th>BVH</th><th>Brute</th></tr></thead><tbody>${row('Completed render','wallMs')}${row('CPU preparation','cpuMs')}${row('CPU BVH update','refitMs')}${row('CPU scene update','sceneMs')}${row('CPU encode','encodeMs')}${row('Submit → done (includes GPU)','queueMs')}${row('GPU visibility raster','visibilityMs')}${row('GPU cascades + gather','cascadeMs')}${row('GPU lighting / shadows / reflection','shadingMs')}${row('GPU reconstruction','reconstructionMs')}${row('GPU present / overlay','presentMs')}</tbody></table><p>Measured frames: ${report.summary.bvh.wallMs?.n??0} BVH / ${report.summary.brute.wallMs?.n??0} brute. Missing timestamps are shown as —. A partial run may have unequal samples; do not treat it as a balanced comparison.</p><p>The export includes raw samples, p95, camera/scene settings, exact output size, browser and available adapter metadata. CPU and GPU times overlap; don't simply add them.</p><button class="benchmark-button" id="download-benchmark">Download measurement JSON</button>`);
  $('#benchmark-status').textContent=report.status==='complete'?'Completed all four blocks.':`Partial/error: ${report.reason}`;
  $('#download-benchmark').onclick=()=>downloadJSON(report);
 };
};
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('.renderer-panel').requestFullscreen();}catch{toast('Fullscreen is unavailable in this browser.');}};
$('#snapshot').onclick=async()=>{if(!renderer)return;try{const blob=await renderer.capture();if(!blob){toast('Unable to capture this frame.');return;}const a=document.createElement('a');a.download='cascade-lab.png';a.href=URL.createObjectURL(blob);a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);toast('Frame saved');}catch{toast('Unable to capture this frame. Please try again.');}};
let canvas=$('#scene-canvas');let drag=null;
const vp=$('#viewport');vp.addEventListener('pointerdown',e=>{if(benchmarking||e.target.tagName!=='CANVAS')return;drag={x:e.clientX,y:e.clientY};vp.setPointerCapture(e.pointerId);vp.classList.add('dragging');});vp.addEventListener('pointermove',e=>{if(benchmarking||!drag)return;settings.cameraYaw=Math.max(-.85,Math.min(.85,settings.cameraYaw-(e.clientX-drag.x)*.004));settings.cameraPitch=Math.max(-.15,Math.min(.55,settings.cameraPitch+(e.clientY-drag.y)*.003));drag={x:e.clientX,y:e.clientY};});function endDrag(){drag=null;vp.classList.remove('dragging');}vp.addEventListener('pointerup',endDrag);vp.addEventListener('pointercancel',endDrag);vp.addEventListener('wheel',e=>{e.preventDefault();if(benchmarking)return;settings.distance=Math.max(settings.scene==='large'?16:8,Math.min(settings.scene==='large'?44:22,settings.distance+e.deltaY*(settings.scene==='large'?.016:.008)));},{passive:false});
window.addEventListener('keydown',e=>{if(benchmarking||dialog.open||['INPUT','SELECT','BUTTON','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();setRunning(!settings.running);}if(e.key.toLowerCase()==='r')resetCamera();if(e.key.toLowerCase()==='g')$('#enable-gi').click();if(e.key.toLowerCase()==='p')$('#show-probes').click();if(e.key.toLowerCase()==='f')$('#fullscreen').click();});
let benchmarking=false,frameInFlight=Promise.resolve(),benchmarkAbort=null,renderer,gpuFault=null,isFallback=false,fpsHistory=[],frames=0,last=performance.now(),statTime=last,statFrames=0;
async function fallback(reason){console.warn('WebGPU unavailable:',reason);isFallback=true;renderer?.destroy();const replacement=canvas.cloneNode();canvas.replaceWith(replacement);canvas=replacement;renderer=await new FallbackRenderer().init(canvas);$('#engine-status').textContent='WebGL preview';$('#render-api').textContent='WEBGL 2';$('#fallback-notice').hidden=false;$('#fallback-notice').onclick=()=>openInfo(`<div class="eyebrow">COMPATIBILITY MODE</div><h2>A preview, not a substitute.</h2><p>This browser or GPU could not initialize WebGPU. You are seeing a rasterized WebGL preview with animated geometry and conventional lights. Radiance cascade compute shaders are not running.</p><p>Try a current Chrome or Edge browser with hardware acceleration enabled, on a WebGPU-capable device.</p><div class="dialog-callout" id="error-details"></div>`);$('#fallback-notice').addEventListener('click',()=>{$('#error-details').textContent=reason.message||String(reason);});$('#probe-count').textContent='—';$('#probe-detail').textContent='WebGPU required';$('#timing-label').textContent='unavailable';if(settings.view===4)$('[data-view="0"]').click();updateLegend();}
async function boot(){try{renderer=new GPURenderer();await renderer.init(canvas);$('#engine-status').textContent='WebGPU active';renderer.onError=e=>{gpuFault=e;console.error(e);};}catch(e){try{await fallback(e);}catch(error){$('#loading').innerHTML='<span>3D rendering is unavailable</span><small>Enable hardware acceleration and reload.</small>';console.error(error);return;}}$('#loading').classList.add('loaded');requestAnimationFrame(frame);}
async function frame(now){if(benchmarking){requestAnimationFrame(frame);return;}if(gpuFault&&!isFallback){const error=gpuFault;gpuFault=null;await fallback(error);}const dt=Math.min((now-last)/1000,.05);last=now;if(settings.running){settings.time+=dt*settings.speed;frames++;}updateScene(settings.time);try{frameInFlight=renderer.render();await frameInFlight;}catch(e){console.error(e);if(!isFallback){await fallback(e);requestAnimationFrame(frame);}else{toast('Renderer interrupted. Reload to try again.');}return;}statFrames++;if(now-statTime>650){const fps=Math.round(statFrames*1000/(now-statTime));$('#fps').textContent=fps;fpsHistory.push(fps);if(fpsHistory.length>16)fpsHistory.shift();$('.metric-sparkline').innerHTML=fpsHistory.map(f=>`<i style="height:${Math.max(2,Math.min(20,f/60*20))}px"></i>`).join('');$('#gpu-time').textContent=renderer.gpuMs!=null?renderer.gpuMs.toFixed(1):'—';$('#visibility-ms').textContent=renderer.passMs?.visibility?.toFixed(2)??'—';$('#reconstruction-ms').textContent=renderer.passMs?.reconstruction?.toFixed(2)??'—';$('#frame-breakdown').textContent=isFallback?'WebGL preview':`Scene ${renderer.sceneMs?.toFixed(1)??'—'} ms · prepare ${renderer.cpuMs?.toFixed(1)??'—'} ms · encode ${renderer.encodeMs?.toFixed(1)??'—'} ms · submit→done ${renderer.queueMs?.toFixed(1)??'—'} ms · completed render ${renderer.wallMs?.toFixed(1)??'—'} ms · ${(renderer.scheduledRays??0).toLocaleString()} interval rays · ${(renderer.uploadBytes/1024).toFixed(0)} KiB geometry/lights`;$('#cascade-ms').textContent=renderer.passMs?.cascades.toFixed(2)??'—';$('#shading-ms').textContent=renderer.passMs?.shading.toFixed(2)??'—';$('#present-ms').textContent=renderer.passMs?.present.toFixed(2)??'—';if(!isFallback&&!renderer.timestamp)$('#timing-label').textContent='not supported';$('#triangle-count').textContent=renderer.triangleCount.toLocaleString();$('#vram').textContent=renderer.memory?(renderer.memory.total/1048576).toFixed(2):'—';$('#mesh-count').textContent=String(renderer.meshCount);$('#cpu-time').textContent=renderer.cpuMs!=null?renderer.cpuMs.toFixed(1):'—';$('#bvh-status').textContent=isFallback?'Raster preview':settings.bvh?`${renderer.nodeCount.toLocaleString()} nodes`:'Brute force';syncBVHControls();$('#frame-count').textContent=String(frames).padStart(4,'0');const t=settings.time;$('#timecode').textContent=`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}.${String(Math.floor(t%1*100)).padStart(2,'0')}`;statFrames=0;statTime=now;}requestAnimationFrame(frame);}
const initialScene=new URLSearchParams(location.search).get('scene');if(sceneInfo[initialScene])selectScene(initialScene);updateLegend();boot();
