#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
#  ExtractCelestialPort.sh — lift the celestial block OUT of ReSTIRViewport.slang and make it compile as C++
# ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
#  🔴 WHY THIS EXISTS. A previous version of the showcase RE-IMPLEMENTED CelestialSky / CelestialSunDisc /
#     CelestialMoonDisc in C++ and called them "mirrors". That is exactly the thing this project keeps being
#     burned by: a proof that agrees with itself. If the shader's disc maths were wrong, a hand-written mirror
#     would render a perfectly nice picture and prove nothing at all.
#
#     So instead this extracts the REAL TEXT of those functions from the shipping shader and compiles it. If
#     someone edits CelestialMoonDisc in the shader, the next render changes. That is the whole point.
#
#  The extraction is line-delimited by markers in the shader itself rather than line numbers, so it does not
#  silently grab the wrong region when the file moves around.
# ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
set -eu

Root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
Viewport="$Root/Engine/Shaders/ReSTIRViewport.slang"
Output="${1:-/tmp/CelestialPort.inc}"

# ── 1. the record struct, verbatim ───────────────────────────────────────────────────────────────────────────────────────────────
#    Ends at the `layout(std430 ...)` line, which is GLSL-only and cannot compile as C++.
Struct="$(sed -n '/^struct CelestialRecord$/,/^};$/p' "$Viewport")"

# The media file is a separate include; it needs the same swizzle/out-param rewriting, and it must come AFTER
#    the record struct it reads. Emitted here rather than by a second script so the two can never get out of order.
Media="$(cat "$Root/Engine/Shaders/CelestialMedia.slang")"

# ── 2. the celestial functions, verbatim ─────────────────────────────────────────────────────────────────────────────────────────
#    From the atmosphere-unpack helper through the end of CelestialSky.
Functions="$(sed -n '/^AtmosphereParameters CelestialAtmosphereOf/,/^}$/p;
                     /^vec3 CelestialObserver/,/^}$/p;
                     /^vec3 CelestialSunDisc/,/^}$/p;
                     /^vec3 CelestialSunGlare/,/^}$/p;
                     /^vec3 CelestialAerialPerspective/,/^}$/p;
                     /^vec3 CelestialFlareHue/,/^}$/p;
                     /^vec2 CelestialFlareScreenUv/,/^}$/p;
                     /^vec2 CelestialFlareSunUv/,/^}$/p;
                     /^vec3 CelestialFlareGhostsScreen/,/^}$/p;
                     /^vec3 CelestialFlareHaloScreen/,/^}$/p;
                     /^vec3 CelestialFlareStreakScreen/,/^}$/p;
                     /^vec3 CelestialFlareStarburstScreen/,/^}$/p;
                     /^uint CelestialFlareElements/p;
                     /^vec3 CelestialFlareStreak(CelestialRecord sky, vec3 rayDirection/,/^}$/p;
                     /^vec3 CelestialFlareGhosts(CelestialRecord sky, vec3 rayDirection/,/^}$/p;
                     /^vec3 CelestialFlareStarburst(CelestialRecord sky, vec3 rayDirection/,/^}$/p;
                     /^vec3 CelestialFlareHalo(CelestialRecord sky, vec3 rayDirection/,/^}$/p;
                     /^vec3 CelestialLensFlare/,/^}$/p;
                     /^vec3 CelestialMoonDisc/,/^}$/p;
                     /^vec3 CelestialSky/,/^}$/p' "$Viewport")"

if [ -z "$Functions" ]; then
    echo "ExtractCelestialPort: found no celestial functions in $Viewport" >&2
    exit 1
fi

# ── 3. the flag constants and step budget the functions reference ────────────────────────────────────────────────────────────────
# ⚠️ The flag #defines are NOT emitted. CelestialUniform.h already declares them as constexpr, and re-defining
#    them as macros breaks that header. Better still: leaving them out means the extracted SHADER code binds to
#    the C++ header's values, so if the two ever disagreed the render would visibly break. The gate asserts the
#    numbers match, so this is a cross-check rather than a gap.
Constants="$(grep -E '^#define kSkyViewSteps|^#define kSkySunSteps|^#define kGlare|^#define kAerial|^#define kFlareElement|^#define kMedia' "$Viewport")"

{
    echo "// GENERATED by Scratchpad/ExtractCelestialPort.sh from Engine/Shaders/ReSTIRViewport.slang."
    echo "// Do not edit. This is the SHIPPING shader text, compiled as C++."
    echo
    echo "$Constants"
    echo
    echo "$Struct"
    echo
    echo "$Media"
    echo
    echo "$Functions"
} \
| sed -E '
    # GLSL swizzles become member calls on the shim types.
    s/\.(xyz|xy|yz|xz|zw)\b([^(])/.\1()\2/g
    # GLSL out-parameters become C++ references.
    s/\bout +(vec[234]|float) +/\1\& /g
    # The kernel reads a storage buffer; the harness supplies one record.
    s/\bCelestial\[0\]/gCelestialRecord/g
' > "$Output"

# ── 4. report, so a silent partial extraction is impossible to miss ──────────────────────────────────────────────────────────────
Count="$(grep -cE '^(vec3|uint|AtmosphereParameters) Celestial' "$Output")"
echo "ExtractCelestialPort: wrote $Output ($(wc -l < "$Output") lines, $Count celestial functions)"
if [ "$Count" -lt 6 ]; then
    echo "ExtractCelestialPort: expected at least 6 celestial functions, found $Count" >&2
    exit 1
fi
